### ISSUE TITLE
question regarding encoding of Siksa guru

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#103]
@aditiagunawan,

Can you check this encoding please?
```
<app><lem type="norm">tumiṅgalakəna</lem><rdg wit="#A">tumigala:kna</rdg><rdg wit="#B">tumigalakna</rdg><rdg wit="#C">tu<unclear>maṅga</unclear><gap reason="lost"/></rdg></app>
```
Something seemed wrong, while I was working on the punctuation.

Thanks, 
Best

**Comment by ajaniak** [comment]
same here
```
<app><lem type="emn">utər</lem><rdg wit="#A">Utar</rdg><rdg wit="#B">Utir</rdg><rdg wit="#C">Uta<gap reason="lost"/></rdg></app>
```

**Comment by arlogriffiths** [comment]
@ajaniak : what is the irrgularity you observe and what is the connection with punctuation? do you mean that `<gap reason="lost"/>` should be complete with @quantity and @unit?

**Comment by ajaniak** [comment]
Yes in both those context, the `<gap/>` needs to be completed. It is an old version of the encoding before the introduction of the `<lacunaStart/>` and `<lacunaEnd/>`.

**Comment by ajaniak** [comment]
In SMG: 
```
<app><lem wit="#A">paknanya pasuklasvanita lavan maṅəyəh</lem><rdg wit="#B" cause="lexical">Anada Aṅəyə pa<gap reason="lost"/></rdg></app>
```
```
<app><lem type="norm">hyaṅ</lem><rdg wit="#A">hya</rdg></app> atma, lumaku paknanya, pamətuan ikaṅ hədap, ya</lem><rdg wit="#B"><gap reason="lost"></gap></rdg></app>
```

**Comment by arlogriffiths** [comment]
@ajaniak : thanks!
@aditiagunawan : please make the necessary corrections and then close this issue.

**Comment by aditiagunawan** [comment]
@ajaniak 

Done! Would you like to check it?

**Comment by ajaniak** [comment]
It should be good! I will let you know if I see something else
