### ISSUE TITLE
display of <lacunaStart>/<lacunaEnd>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#104]
it seems the autogenerated message should be completed with a _point final_.

<img width="347" alt="Capture d’écran 2023-01-06 à 14 20 27" src="https://user-images.githubusercontent.com/835603/210950949-16cbf3d5-b621-48cf-a800-5a22fba99621.png">

also, why is there no space between ... and ti?

**Comment by ajaniak** [comment]
I have pushed the code 
<img width="352" alt="Capture d’écran 2023-01-06 à 09 07 46" src="https://user-images.githubusercontent.com/33328906/210957857-edb48281-38a7-464d-b9ec-b17ddacc0775.png">

**Comment by arlogriffiths** [comment]
thanks!
