### ISSUE TITLE
Issue structure SKK

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#106]
@aditiagunawan, 

It seems you have changed the structure of SKK deleting the div 23. You haven't updated the @xml:id of all the structural elements to adapt them to this change. And mostly you have to apply this also to the translation. 

Can you make the necessary changes ? I can do it if you want but I need to know what you are deleting and what you are keeping. 

Best,

**Comment by aditiagunawan** [comment]
Dear Axelle,

I have adjust the xml file. Please check is there still any error. 

Best,
Aditia

**Comment by ajaniak** [comment]
Yes, it is good! Thanks
