### ISSUE TITLE
display of teiHeader

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#109]
1. in the screenshot below, a `<note>` in the code is not displayed: can you propose a display for notes in this context?
2. can you avoid the random cutting of words that we find in the right margin of our display?
<img width="545" alt="Capture d’écran 2023-02-01 à 15 29 46" src="https://user-images.githubusercontent.com/835603/216011865-8160fc5a-0255-47c3-b770-a71c195c7306.png">

**Comment by arlogriffiths** [comment]
also, it would be better to display the translation not in italics but enclosed in ‘...’

<img width="538" alt="Capture d’écran 2023-02-01 à 16 12 36" src="https://user-images.githubusercontent.com/835603/216021466-342ce455-99b5-410b-bba1-f35b7e3105f8.png">

**Comment by ajaniak** [comment]
1. done
2. You have asked for a text-break to cut the url given for some witnesses. I have deleted it, but it will have other consequences.
3. done

<img width="572" alt="Capture d’écran 2023-02-01 à 11 49 48" src="https://user-images.githubusercontent.com/33328906/216022721-3fbfcd6d-1185-419a-a39c-8848071adc0b.png">
