### ISSUE TITLE
import of translation from gdoc to xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#110]
@ajaniak — are you able to automatically overwrite the present contents of Aditia's translation xml files from the gdocs that he has for the translations, with retention of formating (italics), footnotes, etc.? The ideal would be if this process could be repeated if further changes need to be made. If so he'll give you access to the relevant files.

**Comment by ajaniak** [comment]
No there are no automatic way to do this. I would have to write several layers of code to achieve this.

**Comment by arlogriffiths** [comment]
ok. is there any partial automatization that you could achieve without much code-writing, e.g. for the italics and/or the footnotes?

**Comment by ajaniak** [comment]
I can take a look at the files, but there will always be a part I will have to do manually

**Comment by arlogriffiths** [comment]
I have just given you access to the file which has seen most change since Aditia first manually copy/pasted a draft translation into the corresponding xml file, i.e. DHARMA_CritEdSiksaKandangKaresian_transEng01.xml.

it would save Aditia a lot of time if the tags `<foreign>` and `<note>` could be wrapped around any segments formatted in italics or placed in footnotes, respectively, in the gdoc. do you think that is achievable?

NB: this file is still in flux, so don't do more than testing at this stage and don't spend a lot pf time on coding, if the above request cannot be fulfilled without much coding.

**Comment by ajaniak** [comment]
It will require lots of steps but i have made a quick xslt; not perfect but clean enough for now. 

Aditia has to download the gdoc, open it in Oxygen to dezip it and select the Word > document. Open it. 
Then run the xslt called `DOCX  TO TEI P5` in the section OOXML in the XSLT provided by default in Oxygen. 
From the given output, run the xslt I have pushed: https://github.com/erc-dharma/project-documentation/blob/master/stylesheets/criticalEditions/cleaning-translation.xsl
The resulting file should be good enough meaning it keeps the italic and notes, but some works will have to be done manually after.

**Comment by ajaniak** [comment]
I think this can be closed now.

**Comment by ajaniak** [comment]
All the issue are archived when they are closed, so you will be able to access it if needed. And they are keeping their tags. So you could add a specific one to identify the closed issues you could need to revert to.

**Comment by arlogriffiths** [comment]
Thanks. I was thinking it might be helpful to create some formal doc (in an .md file) on how to obtain encoded XML from translations with notes edited in gdoc/docx. Can you do this, @ajaniak ?

**Comment by ajaniak** [comment]
Well I will do an addition in comments in the files itself and duplicate it in a markdown, but be aware it will probably only run for Aditia's file. If you want to run it on another file, you will have to update the xslt.

**Comment by arlogriffiths** [comment]
thanks. I have made siome changes. do git pull.

could uyou fill in the format instead of ??? under point 1?

regarding the purpose, "overwrite the present contents of Aditia's translation xml files from the gdocs that he has for the translations, with retention of formating (italics), footnote", in the case of future re-use of this xslt, I don't expect there to be any prior contents of the translation XML, to it will only be a question of taking the contents of a google doc and getting it ready for manual block-per-block insertion into the xml file. this being the case, can you indicate which parts of the xslt would become irrelevant?

**Comment by ajaniak** [comment]
I have added the docx comment and nothing must be deleted from the code. But content will need to be added since Aditia's encoding in translation were the structure and prose.

**Comment by arlogriffiths** [comment]
not exactly sure what your response means, but let's close this discussion now.
