### ISSUE TITLE
hyperlink to DHARMA editions in parallels

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#112]
Dear @aditiagunawan ,

Presdently, your parallels are encoded like this:

`<listApp type="parallels">
             <app>
           <note corresp="txt:SMG.21.1">Cf. SMG 21.1: <foreign>ini catur-rahayu ṅaranya, silokanya nihan, mas pirak komala hintən, kaliṅanya, mas ta ma ṅaranna, sabda tuhu təpət bənər, byakta pañcaksara, pirak ta ma ṅaranna, ambək krəta, yogya rahayu, komala ta ma ṅaranna, gəiṅna caaṅ padaṅ, heraṅ ləga loganda aṅən-aṅənna, hintən ma ṅaranna, caṅciṅ səri, səmu imut, səmu guyu, rame ambək.</foreign>.</note>
            </app>
 </listApp>`

We recommend you apply `<ref>` of you are referring to an edition edited by yourself, as follows:

`<listApp type="parallels">
        <app>
         	<note corresp="txt:SMG_21.1">
Cf. <ref target="DHARMA_CritEdSasanaMahaguru.xml#sasanamahaguru_21.01">SMG 21.1</ref>: <foreign>ini catur-rahayu ṅaranya, silokanya nihan, mas pirak komala hintən, kaliṅanya, mas ta ma ṅaranna, sabda tuhu təpət bənər, byakta pañcaksara, pirak ta ma ṅaranna, ambək krəta, yogya rahayu, komala ta ma ṅaranna, gəiṅna caaṅ padaṅ, heraṅ ləga loganda aṅən-aṅənna, hintən ma ṅaranna, caṅciṅ səri, səmu imut, səmu guyu, rame ambək.</foreign>.</note>
        </app>
</listApp>`

**Comment by aditiagunawan** [comment]
Done!

**Comment by ajaniak** [comment]
I have made corrections.
