### ISSUE TITLE
use of <quote> in your critical editions

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#113]
@aditiagunawan — it seems to us that in all cases where you use `<quote>`, it would be better to use `<q>`, because as we say in EGC 3.7, `<quote>` should be reserved for "quotation from another work made by the author of your text", which is n ever your situation.

@ajaniak will make the necessary changes in your xml files.

**Comment by ajaniak** [comment]
done
