### ISSUE TITLE
assign contents to <note> in <listApp type="parallels">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#114]
Derar @ajaniak —

Can you automate conversion of code like `<note sameAs="txt:MDhŚ_08.132-08.133"/>` to `<note sameAs="txt:EdMaDhaSa2005_08.132-08.133">MDhŚ 8.132–133</note>` in my Svayambhu file?

Also, we might bring an end to the transformation picking up on code like `<note sameAs="txt:MDhŚ_08.132-08.133"/>`  to display "MDhŚ_08.132-08.133". At least our recent changes to EGC mean we should probably change that behavior of the transformation, it seems to me.

Do you foresee any complications? It is esp. important that @aditiagunawan's files don't get negatively affected.

**Comment by arlogriffiths** [comment]
see redundance that presently results from the behavior of @sameAs="txt:...":

<img width="880" alt="Capture d’écran 2023-02-16 à 17 49 51" src="https://user-images.githubusercontent.com/835603/219344903-1aa981cb-9827-4a1f-9482-b87f68e6758d.png">

**Comment by ajaniak** [comment]
Both have been done
