### ISSUE TITLE
autogenerated message

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#115]
In this message, can we get a final "." and inserted a comma, like this?

"A gap due to omission intervenes in K, caused by eye-skip."

<img width="517" alt="Capture d’écran 2023-02-16 à 15 42 54" src="https://user-images.githubusercontent.com/835603/219313295-9234766f-9c55-4671-bf39-2e1e88926d50.png">

Please check if other autogenerated message can be changed analogously.

**Comment by ajaniak** [comment]
done
