### ISSUE TITLE
unwanted behavior triggered by presence of <lg> inside <rdg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#116]
Dear @ajaniak —

In svayambhu_07.13, there is a long interpolation containing some `<lg>`s. At the moment, the display inserts TRANSLATION headongs and repeats the relevant apparatus entry number 852 twice inside the display of the relevant `<rdg>`. is the encoding correct? If yes, can you get the display to behave as desired?

<img width="1295" alt="Capture d’écran 2023-02-16 à 17 27 26" src="https://user-images.githubusercontent.com/835603/219340461-e791b4d0-a592-4335-bbfc-af5ac577a87a.png">

**Comment by ajaniak** [comment]
It should be good now
<img width="1349" alt="Capture d’écran 2023-02-20 à 11 02 08" src="https://user-images.githubusercontent.com/33328906/220074071-27efca04-ab1f-48f0-82f4-c3f7754af354.png">

**Comment by arlogriffiths** [comment]
great, thanks!
