### ISSUE TITLE
use of <list> in edition

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#118]
Dear @zakariyaaminullah ! We have just revised §8.8.2 of the Encoding Guide where we now discourage use of `<list>` inside text editions. Actually, the only instance where it is used in any of our editions is in your CK. See the screenshot. Could this be reencoded without using `<list>`?

<img width="1333" alt="Capture d’écran 2023-03-02 à 15 50 09" src="https://user-images.githubusercontent.com/835603/222378459-8e0c4fa2-d5e5-492a-9439-0a0b148b6df6.png">

**Comment by arlogriffiths** [comment]
@zakariyaaminullah — please react a.s.a.p.

**Comment by arlogriffiths** [comment]
@zakariyaaminullah : please respond "done" when it's done and close this issue.

**Comment by zakariyaaminullah** [comment]
done
