### ISSUE TITLE
Display: Lost of space on two <app>s

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#12]
Dear all,

I find a problem with the transformation of two `<app>`s for two separates words in juxtaposition, for example
`<app><lem type="norm">tañjәr</lem><rdg wit="#A">tajǝr</rdg><rdg wit="#B"><gap reason="lost"/></rdg></app> 
<app><lem type="emn" source="bib:Atja+SalehDanasasmita1981_03">jaya</lem><rdg wit="#A">ya</rdg><rdg wit="#B"><gap reason="lost"/></rdg></app>`

I put the space between these two `<app>`, but is missing in the transformation. 

Thanks,

**Comment by ajaniak** [comment]
Can you please send me the screenshot of this issue, since I don't have it in my computer?

Thanks

**Comment by aditiagunawan** [comment]
Here it is:

<img width="943" alt="Screenshot 2021-02-18 at 09 06 34" src="https://user-images.githubusercontent.com/55530631/108325014-ea1b7d00-71c8-11eb-996f-5991d1377b29.png">

**Comment by ajaniak** [comment]
I am sorry but i don't have it, or am I not identifying the right part of the text? 

<img width="884" alt="Capture d’écran 2021-03-01 à 11 46 55" src="https://user-images.githubusercontent.com/33328906/109486998-ecf95600-7a83-11eb-9f1e-b6b828fb19a9.png">

**Comment by aditiagunawan** [comment]
Wow, now I see the problem. This is happen when we use safari, but it's good in chrome. 

Thanks Axelle!
Best,
Aditia

**Comment by ajaniak** [comment]
Well, I will investigate the basic parser set up of safari then. I might be a issue for future users if all the displays are unstable.
