### ISSUE TITLE
Generated Index in LaTex

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#120]
Dear @ajaniak 

Here is the list of adjustments for the generated Index that you made:

- [x] Exclude the `<rdg>` in making the index
- [x] The reference in the index refers to xml:id which is not always in accordance to the html files, especially if we have ślokas or `<lg>`. The numbering in xml:id continues the preceding number of paragraph, but the number itself is absent in the HTML. Since the latex editions follow the paragraph numbering in html, I wonder whether we can make another numbering system or xml:id for `<lg>` or ślokas, for instance skk_11.02a or skk_11.02.01 or something like that. The logic is that the `<lg>`, in my case, belongs to the preceding paragraph. In the index we find \emph{acara}: SKK 11.22, while it should be SKK 11.20. This is due to the existence of two `<lg>` before the paragraph in question.
- [x] Please render the word with hyphen as a single entry, for instance abaṅ-abaṅan (SKK 11.15), not abaṅ and abaṅan.
- [x] For the display, It will be nice if you make a template \glos{entry}{reference}{empty}{empty}.
- [x] Please eliminate the leading zeros: SKK 1.1 instead of SKK 01.01

Thanks,
Aditia

**Comment by ajaniak** [comment]
I don't understand why you want another numbering system, if you don't count the `<lg>`; why not keep SKK 11.20?

**Comment by ajaniak** [comment]
@arlogriffiths I have added the counter when more than one occurrence appears in the same paragraph.

**Comment by arlogriffiths** [comment]
@aditiagunawan — can this be closed now? what about the two check boxes above that haven't been checked yet?

This is an example of the fact that you often ignore github issues and are not alert in ensuring that Axelle soon gets the feedback she needs.

**Comment by ajaniak** [comment]
Like I have said to Aditia during the latest zoom, I am not a specialist of Latex, he needs to ask Andrew regarding those two points.

**Comment by aditiagunawan** [comment]
@arlogriffiths The two issues have been resolved.

**Comment by ajaniak** [comment]
Ah yes sorry, I am sorry I am mixing my issues!
