### ISSUE TITLE
log of manual changes that Aditia had to make to generate his dissertation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#121]
Aditia has pushed the manually changed edition files to aditia-phd/transformation with the titles 99siksaguru-generated-manual.tex, 99sasana-generated-manual.tex, and 99siksakandang-generated-manual.tex. Here is a log of the manual changes he made that should ideally become unnecessary after updates to the XML by modifying the transformation XLST.

- [x] 1. Aditia changed the chapters that were previously automatically numbered so that the chapter number does not appear, by inserting * before the parameter {...} of \eledsubsection. Example:

- this chapter heading \begin{pages}\begin{Leftside}\beginnumbering\pstart{}\skipnumbering\eledsubsection{Pure Circle of Three Bodily Domains}\pend
- was changed to \begin{pages}\begin{Leftside}\beginnumbering\pstart{}\skipnumbering\eledsubsection*{Chapter 1: Pure Circle of Three Bodily Domains}\pend

**It would be best if Axelle/Andrew could create an automatic \label for each chapter because it might be needed for later cross-refs.**

- [x] 2. Aditia added paragraph numbering with \numberpstarttrue and \autopar. **Could Axelle/Andrew change the xslt so that these commands are automatically generated?**

- [x] 3. For chapters containing stanzas, Aditia used paragraph numbering  \begin{numberpstart} and \begin{autopar} and manually deleted the numbering of the stanzas according to the display in the HTML. **Could Axelle/Andrew change the xslt to integrate these changes?**

- [x] 4. In the master file, Aditia added a package \usepackage[advancedshiftedpstarts]{reledpar} to remove the white space between paragraphs. This method pulls all the paragraphs to the top margin (so there is still white space between the chunk and the footnote). **Could Axelle/Andrew change the xslt so that this package gets added?**

- [x] 5. Aditia adjusted the alignment of the stanzas manually so that `<l>`s with n="b" get paired on a single line with `<l>`s having n="c", and analogously with `<l n="c">` and `<l n="d">`. **Could Axelle/Andrew change the xslt so that this this layout is generated automatically?**

- [x] 6. To force line breaks, Aditia has inserted commands \ledpb or \lednopb from the page before the blank page for some white spaces. When this didn't work, he used \begin{pages}\begin{Leftside}\resumenumbering to cut a whole paragraph. He ha tried  to use \ledpb and \lednopb for avoiding widow and orphan lines, but often it doesn't work as expected. **Can Axelle/Andrew offer a solution?**

- [x] 7. A lot of unwanted white space (and nearly or fully blank pages) are due to Chapters being automatically created as \eledsection and \begin{pages}\begin{Leftside} based on the presence of `<div>` in the XML. Our suggestion is to replace `<div= "chapter">` with \eledsection without using \begin{pages}. At the same time, we understand that making one chunk out of the whole edition might create new problems to the parallel. **Can Axelle/Andrew comment on this matter and offer a solution?**

- [x] 8. Since the `<note>` in the translation are sometimes quite long, and created lots of infelicities in parallel display of edition/translation,  Aditia manually copied every note into a separate .tex file for a chapter "Commentary" and replaced the `<note>`s by * in the corresponding segment of the edition. **Can Axelle/Andrew offer any more sophisicated way to generate such a separate commentary chapter? (We imagine that manual insertion of the * mark in the edition will still be necessary, but maybe the solution is to move all such commentary notes out of the translation XML into the edition XML? However, that will then of course ruin the nice display of notes to translation that Axelle has set up in the online version of Aditia's editions.**

**Comment by ajaniak** [comment]
The commentary from the translation can be extracted automatically into a separate chapter with `sh tei-to-latex commentary`.

**Comment by ajaniak** [comment]
@aditiagunawan  and @arlogriffiths, 

Checking the solution for point 8, I have made the export toward another chapter, keeping the structure made manually by Aditia. It allows not to move the `<note>` from one xml file to another. Can you check the result and let me know if you find it satisfactory. On the same subject, I don't understand where you expect *: in the translation or in the edition? can you clarify this matter please?

**Comment by aditiagunawan** [comment]
> 

Dear Axelle,

Your automatic transformation on commentary chapter is nice. However, I still find a problem with the numbering reference to the text where it appears {..1}, {..2}, etc., so we have {\noindent}\textbf{..1}\quad, which do not appear in the my manual work. Do you know what is the problem on this issue?

Best,
Aditia

**Comment by aditiagunawan** [comment]
Dear @ajaniak 

> @aditiagunawan and @arlogriffiths,
> 
> About the point 1, can you confirm that when you say you want a label, you expect this `\begin{pages}\begin{Leftside}\beginnumbering\pstart{}\skipnumbering\eledsection*{Pure Circle of Three Bodily Domains}\label{chap:siksaguru_01}\pend[\vspace{0.2cm}]`?
> Yes, indeed.

> Note on the point 4, I have added the `[\vspace{0.2cm}]` to keep a clean display.
> OK

> About the point 5, can you confirm that you do expect the verse lines numbering with arabic not to be paired ?
The point is that I made adjustment by skipping the numbering in the verse lines and adjusting the layout manually. Now I wonder whether we can make a numbering system for verses, for example śloka 1, śloka 2 for each `<l>`s or another way to numbering verses.

The two screenshots show the manual adjustment on edition and translation:

Verse in edition (without numbering)

<img width="377" alt="Screenshot 2023-04-13 at 00 13 42" src="https://user-images.githubusercontent.com/55530631/231534538-d83fc2c4-fb57-48e5-8805-c5ccb3d934d9.png">

In the translation:
<img width="368" alt="Screenshot 2023-04-13 at 00 14 25" src="https://user-images.githubusercontent.com/55530631/231535124-87e42789-00e7-4d20-a780-b84a151c20de.png">

Overall, the automatic transformation is not yet satisfactory. All the `<note>` in the xml still appears in the translation page (on the main text) (see red box in the screenshot). It should be removed.


<img width="610" alt="Screenshot 2023-04-13 at 00 25 58" src="https://user-images.githubusercontent.com/55530631/231536818-1a44fe3a-e01b-4e0a-a86d-bba97d7dc912.png">

Best,
Aditia

**Comment by ajaniak** [comment]
-[ ] Correcting some missing numbering in commentary
-[ ] Display of stanza not yet as it should (but might be a consequence of a previous decalage - so to watch) 
-[ ] keeping eledsubsection without asterisk
- [ ] Deleting notes still in translation and add a asterisk instead
- [ ] Translation adding numering for paragraphs.
- [ ] numbering all stanza continously in the edition without consideration for the paragraphs.

**Comment by ajaniak** [comment]
@aditiagunawan  I have pushed several solutions on the xslt, can you take a look please?

**Comment by aditiagunawan** [comment]
@ajaniak 

Many thanks Axelle. It is quite good now. Our problem now is only white spaces in Latex (no. 6 and 7).

**Comment by arlogriffiths** [comment]
@aditiagunawan : can check boxes 6 and 7 above now be checked? if so, please do it and close this issue.
