### ISSUE TITLE
An unwanted submodule 

### ISSUE THREAD

**Issue by zakariyaaminullah** [erc-dharma/tfd-nusantara-philology#122]
Dear @ajaniak,

When trying to pull, commit and push the files that I modified, there is a problem as stated as follows:
<img width="1290" alt="Screenshot 2023-03-30 at 12 19 32" src="https://user-images.githubusercontent.com/39810661/228737604-02d55811-ed23-4257-8e1a-8130f4003b12.png">
I think that it started when I was using Visual Studio Code and I am still unfamiliar with its features. That is why there is an unwanted submodule and I do not know how to remove it. Thank you very much!

**Comment by ajaniak** [comment]
Dear @zakariyaaminullah, 

With so little information, it is difficult for me to identify what is wrong. However, since you haven't clone the repository from Visual Code Studio itself, are you sure you have set the path to the repository? It is not because it is shown by default in the versioning panel that the repository have be loaded correctly.

 -  Open Visual Studio, with a complete new window.
 - From the source control panel, select open folder button to load it into the editor

Can you let me know if it could be the issue? 

Best

**Comment by arlogriffiths** [comment]
@zakariyaaminullah : has this problem been solved now?

**Comment by zakariyaaminullah** [comment]
Dear @arlogriffiths @ajaniak,

Sorry for the late response, but it seems that the problem has not been resolved yet. I just tried to do a git pull and git push, then there was the following error message:

Fatal Error! A sequence of more than one item is not allowed as the first argument of fn:translate() ("----+----=", "----+----=") 
60
     [xslt] Failed to process null
61

62
BUILD FAILED
63
/home/runner/work/tfd-nusantara-philology/tfd-nusantara-philology/build-critical.xml:51: Fatal error during transformation using /home/runner/work/tfd-nusantara-philology/tfd-nusantara-philology/project-documentation/stylesheets/criticalEditions/start-edition.xsl: A sequence of more than one item is not allowed as the first argument of fn:translate() ("----+----=", "----+----=") ; SystemID: file:/home/runner/work/tfd-nusantara-philology/tfd-nusantara-philology/project-documentation/stylesheets/criticalEditions/start-edition.xsl; Line#: 1326; Column#: 10
64

65
Total time: 29 seconds
66
Error: Process completed with exit code 1.

It appears that I may have input the incorrect format, and there is a possibility of unexpected values or characters, but I am uncertain.

**Comment by ajaniak** [comment]
I understood what you mean know. This has nothing to do with Visual Code. The github actions is separated and can break for several reasons. It seems here that one or several files aren't well-formed or have en encoding issue breaking the transformation display. I will check it

**Comment by arlogriffiths** [comment]
my impression is that we were still waiting for @ajaniak to report back on what she was going to check.

meanwhile, do git push/pull work again for you, Zaki?

**Comment by ajaniak** [comment]
Yes, I have correct the doublon made in prosody which was breaking the pipeline.

**Comment by zakariyaaminullah** [comment]
I'm happy to report that I was able to successfully perform a git pull/push. Thank you for your help @ajaniak, Pak @arlogriffiths!

Should I close this issue?

**Comment by ajaniak** [comment]
Yes, I am closing it! If you have another issue, feel free to open another issue though.

Best,
