### ISSUE TITLE
Number display in critical edition

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#124]
Several display must evolved in the current XSLT for critical edition:

- [x] First the `@n` attribute for `<lg>` shouldn't be taken into account for the display, it should be automatically numbered
- [x] Secondly, references in gaps and lacunae must be changed for `(§ paragraph number)` to counter level, as described in the previous point.

**Comment by arlogriffiths** [comment]
Thanks. 

Why should the display of numbering of`<lg>` not be based on the value if @n? 
Hadn't we decided yesterday that all displayed block numbers will be the values of @n?

**Comment by ajaniak** [comment]
I have change the code for lg

**Comment by arlogriffiths** [comment]
today it seems we made one more change concerning lg numbering, making it entirely unmandatory. is the code up to date?

**Comment by ajaniak** [comment]
I have pushed this new condition
