### ISSUE TITLE
html not generated

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#125]
why is no html generated for DHARMA_CritEdAstadasaVyavahara.xml?

<img width="721" alt="Capture d’écran 2023-04-16 à 07 12 19" src="https://user-images.githubusercontent.com/835603/232259421-a97125d7-dbbe-4477-9676-c52e6c09fea8.png">

<img width="968" alt="Capture d’écran 2023-04-16 à 07 12 41" src="https://user-images.githubusercontent.com/835603/232259430-5cc92500-96dd-4a8c-ae99-a48340519b2a.png">

**Comment by arlogriffiths** [comment]
now even the index pages aren't accessible any more

![Uploading Capture d’écran 2023-04-17 à 14.53.31.png…]()

**Comment by arlogriffiths** [comment]
problem seems to be solved now.

**Comment by ajaniak** [comment]
I have changed this morning one of the gihtub action file. However, since I am not sure exaclty why the issue has occured in the first place and can't find information on the matter in github documentation. I can vouch the stability of this solution.
