### ISSUE TITLE
fill in @scriptref in teiHeader

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#126]
@aditiagunawan : I see in SiksaGuru that you haven't yet encoded the values of @scriptef:

`<handDesc>
              <handNote xml:id= "A_H1" scriptRef="class:... maturity:...">
			 <p>The only hand of the manuscript, black ink, Old West Javanese quadratic script.</p>
            </handNote>
  </handDesc>`

Go to [opentheso.huma-num.fr/opentheso/?idt=th347](https://opentheso.huma-num.fr/opentheso/?idt=th347) to learn about DHARMA controlled vocabularies. Pick the relevant numerical IDs from the script class and script maturity vocabs. (See also the [unpublished Memo on DHARMA controlled vocabularies ](https://docs.google.com/document/d/12HypwZj4ym6-SX6T7o8Qwl51gl5k1gvux_iOyJfM2zs/edit#heading=h.hvuqpmaxfaba)for more background on the class/maturity distinction.)

Please review all your editions on this point.

Here is an example for what I have filled in in the case of the codex unicus (Perpusnas L882) of Aṣṭādaśavyavahāra:

`<handDesc>
	<handNote xml:id= "MS_H1" scriptRef="class:83239 maturity:83215"> 
		<p>The only hand of the manuscript, black ink, neat Balinese script.</p>
	</handNote>
</handDesc>`

I am also sending this to @andreaacri  and @zakariyaaminullah  who probably need to make adjustments in the teiHeaders of their editions as well.

**Comment by arlogriffiths** [comment]
Seeing the display, I have decided to reformulate the `<p>` as follows:

`<p>Only a single hand is observed: black ink, neat Balinese script.</p>`

Adding @Ilhamkang.

**Comment by aditiagunawan** [comment]
Dear @arlogriffiths 

I have applied `<handDesc><handNote xml:id="MS_SiGuB" scriptRef="class:83241 maturity:83215"></handNote>` for the file DiplEdSiksaGuruPerpusnasL633. It is not validated. I received a message "found attribute "scriptRef", but no attributes allowed here".

Best,
Aditia

**Comment by arlogriffiths** [comment]
I am not sure but my request was intended to concern crit. ed., not dipl. ed. It may be that the schema for dipl. ed. has not yet been updated to allow use of @scriptRef. It's a question for @ajaniak .

**Comment by ajaniak** [comment]
Indeed, the schema for dipl ed doesn't take the`@scriptRef`, I have added it just in case.

**Comment by arlogriffiths** [comment]
thanks. @aditiagunawan , @zakariyaaminullah , @Ilhamkang : please interpret my comment as applying partciularly to your critical edition files.

**Comment by aditiagunawan** [comment]
@arlogriffiths 

Done.

**Comment by arlogriffiths** [comment]
@zakariyaaminullah and @Ilhamkang : please react by making the necessary changes in your crit. ed. files and respond "done" when it's done or "doesn't concern me" if you are not concerned.

**Comment by zakariyaaminullah** [comment]
done

**Comment by Ilhamkang** [comment]
Done

**Comment by arlogriffiths** [comment]
thanks Aditia, Zaki and Ilham! I am closing this issue now.
