### ISSUE TITLE
add constraint to schema for @wit on <rdg>?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#127]
Dear @ajaniak,

I notice that the schema does not reject the following entry where I have forgotten to encode @wit: 

` <app><lem type="emn">nikṣepa</lem><rdg>dikṣepa</rdg></app>`

Can a constraint be added to oblige the encoder to use @wit on `<rdg>` or is there a reason why we don't have such a constraint?

cc to other encoders for their information: @andreaacri, @aditiagunawan, @zakariyaaminullah, @Ilhamkang

**Comment by ajaniak** [comment]
I have just pushed this addition in the schema

**Comment by arlogriffiths** [comment]
thanks!
