### ISSUE TITLE
Different siglum of same element on "source" in the Apparatus

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#13]
Dear Axelle,

I find the case of the different representation of source attribute with the same element in the Apparatus. When we put  "source bib:Atja+SalehDanasasmita1983_03" inside `<lem>` then the siglum becomes  **Ed**, but if it is placed on `<rdg>`, then it becomes **EDASD**. Here is the example:

`<app><lem type="norm" source="bib:Atja+SalehDanasasmita1981_03">nañjərkən</lem><rdg wit="#A">najərkən</rdg><rdg wit="#B"/></app> saṅ hyaṅ sasana krəta, pakənən hәbәl hirup həbəl 
   <app><lem type="emn">ñovana</lem><rdg wit="#A #B">ñavana</rdg><rdg source="bib:Atja+SalehDanasasmita1981_03">ñevana</rdg></app>`

The result is as follows:

<img width="368" alt="Screenshot 2021-02-18 at 09 43 25" src="https://user-images.githubusercontent.com/55530631/108331236-db37c900-71ce-11eb-945f-9a2e1f2cf96c.png">

I would prefer to have **EDASD** on both cases, just to avoid the ambiguity of the siglum.  What do you think?

Best,
Aditia

**Comment by aditiagunawan** [comment]
Just add a little bit: it works well as I expect in the main text (with mouse slide preview), but not in Apparatus at the bottom page. Thanks.

Best,
Aditia

**Comment by ajaniak** [comment]
It should work now

**Comment by arlogriffiths** [comment]
@aditiagunawan : is this problem solved now? if so, please close the issue. (for some reason, at this moment I am unable to trtansform your file to test this myself.)

**Comment by ajaniak** [comment]
the use `<witDetail>` isn't really stable in SiksaKandangKaresian-CritEd, so I withdrew the code to transform this feature from the code. You should be able to transform it now.
