### ISSUE TITLE
"Run failed: Pipeline manuscripts"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#130]
It would be nice if this frequently occurring interruption in our workflow could be resolved.

What about paying a fee to GitHub so they give us more bandwidth, if that is the problem?

**Comment by michaelnmmeyer** [comment]
@arlogriffiths Is the error message more specific?

**Comment by arlogriffiths** [comment]
c'est @Ilhamkang qui m'a renvoyé le message :

<img width="1059" alt="Capture d’écran 2023-05-08 à 13 53 46" src="https://user-images.githubusercontent.com/835603/236755115-0ae928ff-fe49-44e1-9773-470b36ab08b9.png">

tu peux parler du problème avec Axelle? elle connaît bien les soucis que nous avons avec la pipeline tant dans le répo tfd-nusantara-philology que dans les divers répos -epigraphy, quoi que la cause du problème semble tenir à l’API Zotero dans le second cas mais pas dans le premier, si j’ai bien compris Axelle.

**Comment by michaelnmmeyer** [comment]
In this case it's because there's currently an invalid XML file in the repository, namely `DHARMA_CritEdBhuvanakosa.xml`. The file isn't related at all to @Ilhamkang 's commit, thus it's understandably confusing that he's getting an error message even though his own files are valid.

This calls for a more granular build process viz. to only process and validate the texts modified in a given commit instead of all the texts in the repository. It's trivial to do with standard build tools like `make`, but I don't know if this is feasible with github actions, so I'll see that with Axelle.

**Comment by arlogriffiths** [comment]
thanks a lot. @andreaacri's file DHARMA_CritEdBhuvanakosa.xml was generated by Axelle recently based on Andrea'sa code in TEX. I don't have it before my eyes but I presume it still needs a lot of work from Andrea before it can validate. So far, Andrea has little experience with XML encoding and I don't know when I will get around to it. 

Can we get the pipeline to ignore that file, remove it from the repository altogether, or move it into a seperate folder that will be ignored by the pipeline? That way, Andrea can work it at huis leisure without the file becoming an impediment to other team members...

But if it is possible to implement a more granular build process, as you suggest, that will of course be a nicer solution.

**Comment by andreaacri** [comment]
Dear ArloI’m not sure if this is related to the error ‘Pipeline manuscripts workflow run’ that I get every time I upload the file of the Pārthayajña. It validates at my end though.AndreaSent from my iPhoneOn 8 May 2023, at 11:43, arlogriffiths ***@***.***> wrote:﻿
thanks a lot. @andreaacri's file DHARMA_CritEdBhuvanakosa.xml was generated by Axelle recently based on Andrea'sa code in TEX. I don't have it before my eyes but I presume it still needs a lot of work from Andrea before it can validate. So far, Andrea has little experience with XML encoding and I don't know when I will get around to it.
Can we get the pipeline to ignore that file, remove it from the repository altogether, or move it into a seperate folder that will be ignored by the pipeline? That way, Andrea can work it at huis leisure without the file becoming an impediment to other team members...
But if it is possible to implement a more granular build process, as you suggest, that will of course be a nicer solution.
