### ISSUE TITLE
what is the encoding error?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#131]
Dear @michaelnmmeyer !

Could you look into the XML of DHARMA_CritEdSvayambhu.xml and try to determine what is error that explains the irregularity in display starting after 241? See screenshot. Should I use `<quote>` even if the source stanza is unidentified and cannot therefore by quoted? Even so, why does the irregular indenting get applied over onto the following `<div type="dyad">`s whose structure is quite regular?

<img width="1468" alt="Capture d’écran 2023-07-02 à 07 54 59" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/3eb617e1-32b6-4787-af38-64c64ebecfb4">

**Comment by michaelnmmeyer** [comment]
Dear @arlogriffiths

The encoding is OK. There was an issue with the build process, which basically tripped over itself. The output is fine now.
