### ISSUE TITLE
revise Addition Synonyms 236

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#145]
236. Synonyms of Iron Bludgeon
1 parigha, parighāta, astra, ṅa vaklaṅ. 

The intended OJ word is vaṅkəlaṅ, which you should propose as small emendation. This OJ word seems to mean 'closure'. Cf. MW parigha ‘an iron bar or beam *used for locking or shutting a gate*’. So I suggest "Synonyms for Iron Bar".

See Svayambhu 
- §214 ikaṅ maṅvan vuvusən pramādanya, yan iṅ rahina təkaniṅ halanikaṅ maṅvan, kunaṅ yan iṅ vəṅi kahilaṅan ya, iṅ umahnikaṅ adravya ta ya, tan hana doṣanikaṅ aṅvan yan maṅkana, kunaṅ yan ahala *vaṅkəlaṅ*nikaṅ kaṇḍaṅ, tan pinagər kunaṅ, tan vinarah ikaṅ madravya, hilaṅ tekaṅ kəbo riṅ vəṅi, ry umahnikaṅ madravya tuvi, ikaṅ maṅvan umaṅguha pramādanya, maṅəlyanana ta ya irikaṅ hilaṅ.
- there is one more occurrence of vaṅkəlaṅ in a part of Svayambhu that Tim and I haven't edited yet (ms. L fol. 36, line 22): pahayun· vaṁklaṅana hikaṅ umaḥ.

See also Prasasti Garaman 2r3–4 
- ma⟨⟨ṅ⟩⟩kanimitta pinakahujuṁ-ka§(2r4)raṁ pamiṅgir· vaṁklaṁni matiṅkaḥ bubuhan
- Boechari: “since they were made the points of the corals at the borders, forming the support for those who were arranging their allotted task,”
- AG tentatively: “since they served as the peripheral village (? hujuṅ karaṅ) at the borders, closure of those arranging tasks”

Van der Tuuk (KBW vol. III, p. 508), cites the word with an unidentified lexicographic source that uses some of the same words as CK, besides the forst passage from Svayambhu cited above.

<img width="294" alt="Capture d’écran 2024-03-12 à 08 32 37" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/15d9c976-eac5-4771-8a03-61ae6f37b6b1">

**Comment by zakariyaaminullah** [comment]
Thanks Pak! I will discuss it in the upcoming translation.

**Comment by arlogriffiths** [comment]
We will have to discuss whether there is any need to propose an integral translation for the part of the text, but in any case you will need to offer a commentary.

One more detail on this item.

-  parighaḥ parighāte ’stre ’pyogho vr̥nde ’mbhasāṁ raye | : insert space to get ’py ogho. 
- It would really be wonderful if you could learn to pay closer attention to word divisions in quoting Sanskrit passages.
