### ISSUE TITLE
formatting and referencing

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#146]
1. when citing page numbers, insert a space between p. and the number
2. for AṬS citations: citing only the page is insufficient, as the edition in question covers four parts; you should download all volumes from the links you can find here:
	http://opac.sub.uni-goettingen.de/DB=1.20/SET=4/TTL=1/FAM?PPN=728194392
and then make sure you specify the part number. For example, under 351, it should be like this:

    AṬS III.176: alañjaraḥ syān maṇikaḥ alañjaradvayaṃ jāḍīti khyāte | maṇir eva maṇikaḥ | svārthiko ’tra kaḥ |

     See http://gretil.sub.uni-goettingen.de/gretil_elib/Ama9143__Amarasimha_Namalinganusasana_2COMMs-Ksir-Sarv_3_1917_TSS_51.pdf

3. assemble consecutive lines of a given verse text in a single note. Instead of

    AbhCM 665cd: nūpuraṁ tu tulākoṭiḥ pādataḥ kaṭakāṅgade ||
    AbhCM 666ab: mañjīraṁ haṁsakaṁ śiñjinyaṁ śukaṁ vastramambaram | 

please implement this pattern:

    AbhCM 665cd–666ab: nūpuraṁ tu tulākoṭiḥ pādataḥ kaṭakāṅgade || 666ab: mañjīraṁ haṁsakaṁ śiñjinyaṁ śukaṁ vastramambaram | 

4. include daṇḍas inside `</foreign>`, rather than outside

**Comment by arlogriffiths** [comment]
1. Now you have many cases like these `<note>DhK p. 15: <foreign>bhūtikaṁ kattr̥ṇe khyātaṁ bhūtikaṁ syād yavānikā | </foreign></note><note>NĀS p. 9.10: <foreign>bhūtikaṁ bhūminimbe ca yavānyaṁ ca tr̥ṇe tathā || </foreign></note>` with spaces between danda and `</foreign>`. You should remove all those spaces.

2. And cases like these `<note>AbhCM 1153: <foreign>vaṁśo veṇur yavaphalas <seg type="highlight">tvacisāras</seg> tr̥ṇadhvajaḥ | </foreign> <foreign>maskaraḥ śataparvā ca svanavānsa tu kīcakaḥ || </foreign></note>` where a single verse is interrupted by `</foreign> <foreign>`. You should remove these interruptions.

3. And cases like these `<note>AK 2.7.33cd–34ab: <foreign>kramādātithyātitheye atithyarthe 'tra sādhuni || </foreign> 2.7.34ab: <foreign>syur āveśika āgantur atithir nā gr̥hāgate | </foreign> </note>` where a set of contiguous verse lines is interrupted by `</foreign> 2.7.34ab: <foreign>` with a redundanty repetition of the verse/pāda numbers for the second part.

Jika Zaki bisa belajar bekerja dengan lebih fokus pada hal-hal seperti itu, maka tugas saya akan menjadi lebih ringan.

**Comment by zakariyaaminullah** [comment]
I have indeed noted these cases yesterday and will work on them today, but thank you for the reminder. I will close the comment when finished. Regarding the Amarakośa quotation, should we align it with the edition and numeration from the Adyar version as Mr. Dominic sent yesterday?

**Comment by arlogriffiths** [comment]
which edition are you following so far? I don’t think it really matters which edition you choose, as lomng as you say it clearly and implement the choice consistently. I have no iobjection to adopting the Adyar edition as edition of reference. when you are in Pondicherry, you may ask Dominic whether he has specific reasons to choose that one.

Le 14 mars 2024 à 13:05, zakariyaaminullah ***@***.******@***.***>> a écrit :



I have indeed noted these cases yesterday and will work on them today, but thank you for the reminder. I will close the comment when finished. Regarding the Amarakośa quotation, should we align it with the edition and numeration from the Adyar version as Mr. Dominic sent yesterday?

**Comment by zakariyaaminullah** [comment]
So far, I've been following the e-text edition provided by Dhaval Patel. Alright, Pak, once I'm in Pondicherry, I'll ask Prof. Dominic directly. By the way, could you specify what exactly I should revise for the third case from your comment? This case arose because I've just implemented what you mentioned in the previous comment about this structure:

`AbhCM 665cd–666ab: nūpuraṁ tu tulākoṭiḥ pādataḥ kaṭakāṅgade || 666ab: mañjīraṁ haṁsakaṁ śiñjinyaṁ śukaṁ vastramambaram |`

Do you have any thoughts on how to overlook excessive repetitions of verse/line numbers but still acknowledge that these are different verses/lines from those before or after?

**Comment by arlogriffiths** [comment]
Sorry for slow response. I see that without my response, you have taken a decision I don’t approve of, with cases like this:

`<note>AK 2.4.60cd–61ab: <foreign>pītadruḥ saralaḥ pūtikāṣṭhaṁ cātha drumotpalaḥ ||</foreign> 61ab: <foreign>karṇikāraḥ parivyādho lakuco likuco ḍahuḥ |</foreign></note>`

Since 61ab follows immediately after 60cd and since || means that one stanza ends and another begins, this manner of encoding is redundant. Please do it like this, which is also what I did  in the example I previously sent you:

`<note>AK 2.4.60cd–61ab: <foreign>pītadruḥ saralaḥ pūtikāṣṭhaṁ cātha drumotpalaḥ || karṇikāraḥ parivyādho lakuco likuco ḍahuḥ |</foreign></note>`
