### ISSUE TITLE
attention to my typos and to inserting spaces in Skt.

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#157]
Let's take a a look at https://github.com/erc-dharma/tfd-nusantara-philology/commit/3332ac9f8f7470f0600bac79e96ee19504514b53.

**You are still too often blindly copy/pasting. This cannot be accepted from a philologist.**

1. You must pay careful attention to inserting spaces in Skt. parallels quoted from e-texts
<img width="833" alt="Capture d’écran 2024-03-26 à 06 05 48" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/1eda6655-3928-41c3-9553-1a1328e3fdf8">

- while making this correction, you should have though of inserting space between puṁsy and atha.

<img width="1520" alt="Capture d’écran 2024-03-26 à 06 06 59" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/bf3dae26-0627-454c-b36f-fca02485e604">

- while making this correction, you should have though of inserting space between dhiṣṇyam and āvasathaṁ
- in this way, you should shystematically try to understand and make visible the word breaks when pasting passages from e-text. Since our e-texts are mainly based on Devanagari editions, they systematically lack typed spaces where we can insert them in transliteration while we cannot insert them in Devanagari.

2. you must pay close attention to typos in my comments and correct them when pasting into you file, especially in parts that will be visible for outside readers

<img width="1528" alt="Capture d’écran 2024-03-26 à 06 11 04" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/b1ea50c3-0671-4d61-8bc2-b2beef8dbcc8">

- you should have corrected "use" to "used" and "hyou" to "you"

<img width="836" alt="Capture d’écran 2024-03-26 à 06 13 53" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/3622ded8-a358-4190-9c64-d6831eff5147">

- you should have corrected "Forhead" to "Forehead"

<img width="1497" alt="Capture d’écran 2024-03-26 à 06 12 53" src="https://github.com/erc-dharma/tfd-nusantara-philology/assets/835603/c13bb3ff-4085-40b9-a6b1-1b6641093441">

- you should have corrected "connectioon" to "connection"

**Comment by zakariyaaminullah** [comment]
I've tried my best to meticulously handle the Sanskrit passage that I pasted into the XML, Pak Arlo. However, the problem arises because there's so much text, I often find myself getting overwhelmed. But I'm still committed to learning and being thorough. Regarding your notes, I think it's okay to leave them as typos because what I'm emphasizing are your ideas, which I'll later incorporate into comments in the translation. In the future, I'll make an effort to clean up such typos when there are important notes from you.
