### ISSUE TITLE
Small modification concerning @cause="eyeskip"

### ISSUE THREAD

**Issue by m-schoettel** [erc-dharma/tfd-nusantara-philology#16]
The display is great, see an example here:

<img width="1107" alt="Screenshot 2021-03-11 at 13 52 20" src="https://user-images.githubusercontent.com/26002486/110790406-4a09be80-8271-11eb-853c-78800f23f644.png">

But we would like '(eyeskip)' not to be in italics. Thank you!

**Comment by ajaniak** [comment]
Done
