### ISSUE TITLE
your can use @rend="check" for things to check

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#18]
Dear @m-schoettel @aditiagunawan @andreaacri @lubint,

It's not yet described in the guide, but already available: you can use `@rend="check"` like this:

`<app><lem type="conj" rend="check">aṅkǝn</lem><rdg wit="#L #K">hankan</rdg></app>`

and will; get the following display:

<img width="264" alt="Capture d’écran 2021-03-12 à 12 05 48" src="https://user-images.githubusercontent.com/835603/110932094-518d9e00-832b-11eb-94e9-675a071295d4.png">

Please respond to confirm you have taken note. Then I'll close this issue again.

**Comment by ajaniak** [comment]
It is already in the guide p.79

**Comment by arlogriffiths** [comment]
Thanks for pointing me to that part of the guide which I had myself not yet reached!

**Comment by lubint** [comment]
Dear Arlo,
I have taken note.
Best,
Tim

From: arlogriffiths ***@***.***>
Reply-To: erc-dharma/tfd-nusantara-philology ***@***.***>
Date: Friday, March 12, 2021 at 6:08 AM
To: erc-dharma/tfd-nusantara-philology ***@***.***>
Cc: "Lubin, Tim" ***@***.***>, Mention ***@***.***>
Subject: [erc-dharma/tfd-nusantara-philology] your can use @rend="check" for things to check (#18)


Dear @m-schoettel<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fm-schoettel&data=04%7C01%7Clubint%40wlu.edu%7Cc85c0d211f834fc7d64308d8e54720ec%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637511440963834827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jadapCw9gYSp6vpnVaxOsdQxS%2F%2FkB9r1LgM2FjKjBHc%3D&reserved=0> @aditiagunawan<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faditiagunawan&data=04%7C01%7Clubint%40wlu.edu%7Cc85c0d211f834fc7d64308d8e54720ec%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637511440963844820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wcD%2Fl905k5hEgW7mO4zkVTQ%2F%2FV2S487rZ3X6AwFJC3A%3D&reserved=0> @andreaacri<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandreaacri&data=04%7C01%7Clubint%40wlu.edu%7Cc85c0d211f834fc7d64308d8e54720ec%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637511440963844820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DPpKVba2MN0cGO%2BLGjx1n4kZoZSQNN1dba%2FE2Cxf12k%3D&reserved=0> @lubint<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flubint&data=04%7C01%7Clubint%40wlu.edu%7Cc85c0d211f834fc7d64308d8e54720ec%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637511440963854812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6JK2SGFnh1PlmfFsqot6bOlYncvKlztZ5Vk%2F3hn%2BW7Y%3D&reserved=0>,

It's not yet described in the guide, but already available: you can use @rend="check" like this:

<app><lem type="conj" rend="check">aṅkǝn</lem><rdg wit="#L #K">hankan</rdg></app>

and will; get the following display:

[Image removed by sender. Capture d’écran 2021-03-12 à 12 05 48]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F835603%2F110932094-518d9e00-832b-11eb-94e9-675a071295d4.png&data=04%7C01%7Clubint%40wlu.edu%7Cc85c0d211f834fc7d64308d8e54720ec%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637511440963854812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O9MkDc7p3kaupKee0QgQreWbOi%2FXvNRrrRpnCT5f%2BdY%3D&reserved=0>

Please respond to confirm you have taken note. Then I'll close this issue again.

**Comment by arlogriffiths** [comment]
@lubint : thanks!

@m-schoettel and @aditiagunawan : I don't understand why you haven't responded to my request for confirmation. Anyhow, I assume you have taken note and am closing this issue now.
