### ISSUE TITLE
non validation of <ab> in Svayambhu-CritEd.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#19]
Dear @ajaniak — what change should I make to make the validation problems concerning use of `<ab>` go away in Svayambhu-CritEd.xml?

**Comment by arlogriffiths** [comment]
PS The problem does not stand in the way of successful transformation...

**Comment by ajaniak** [comment]
You need to stick to your encoding model adding a `<div>` for your trailing `<ab>`. I have made the necessary changes to your file.

**Comment by arlogriffiths** [comment]
Thanks. Presently, the EGC (top of p. 27) states:

"For final colophons, this type of `<p>` or `<ab>` shall be considered the mirror image of text-initial invocations, in the sense that they may stand outside of the final `<div>` but before the end-tag of the containing element `<body>`. And, analogously to the case of `<div>`-level invocations, any colophons at the `<div>` level should be included before the closing tag of the containing element."

This does not seem to mean the same a creating separate `<div>` to enclose the `<ab>`. 

Could you explain which encoding model you are referring to if not the above passage from the EGC? Should the EGC be modified?

**Comment by ajaniak** [comment]
I have added the `<div>`around the colophons and invocations.
