### ISSUE TITLE
jumping from <app> entries in text to their representation at bottom of the file, and back

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#20]
@ajaniak : this is not working in the display at the moment

**Comment by ajaniak** [comment]
Yes I know. You can't have both the popover and the link to go navigate the files on the same elements without some Javascript

**Comment by ajaniak** [comment]
Should be working now

**Comment by arlogriffiths** [comment]
thanks!
