### ISSUE TITLE
Problem of transformation

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#21]
Dear @ajaniak 

I made several update this morning to my file SiksaKandangKaresian-CritEd, and there was no problem, but now suddenly I have a transformation like this: 

<img width="1040" alt="Screenshot 2021-03-16 at 18 22 58" src="https://user-images.githubusercontent.com/55530631/111354026-2afe9880-8686-11eb-83ae-d3bf60fbc3ef.png">

So the `<app>` is taken from the main text to the very right margin with the number. 

I am afraid I made a mistake of something, or this is due to the scenarios update? 

Thanks,
Aditia

**Comment by ajaniak** [comment]
I do not have it, when updating the CSS it takes up to 2 hours to be applied so the issue might have occurs in relation to this. Or I have made a change I don't remember pushing, anyway it seems ok now.

**Comment by aditiagunawan** [comment]
Yes, now it works. 

Thank you.
