### ISSUE TITLE
espace glissé devant virgule dans l'apparat en bas de page

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#22]
@ajaniak : nous avons beaucoup de cas comme ceux-ci

<img width="417" alt="Capture d’écran 2021-03-19 à 05 43 16" src="https://user-images.githubusercontent.com/835603/111732570-0e28b780-8876-11eb-9991-64eced3a472e.png">

`<app><lem wit="#B">mataṅnyan</lem><rdg wit="#A">mantaṅnyan</rdg><rdg wit="#C">mantaṅṅan</rdg></app>`

<img width="350" alt="Capture d’écran 2021-03-19 à 05 37 58" src="https://user-images.githubusercontent.com/835603/111732335-82af2680-8875-11eb-9622-5b5db545843e.png">

 `<app><lem wit="#A #C">sirāmrayatna</lem><rdg wit="#B">sira prayatna</rdg></app>` 

où un espace voire des espaces se glisse(nt) devant virgule(s) dans la présentation. comme l'illustre le premier exemple, l'insertion se trouve tant entre @wit pour `<lem>` et @wit pour premier `<rdg>`, qu'entre des `<rdg>` suivants.

peux-tu identifier la source de l'insertion de ces espaces et l'éliminer?

merci!

**Comment by ajaniak** [comment]
It should be good to go

**Comment by arlogriffiths** [comment]
thanks!
