### ISSUE TITLE
change filenames

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#23]
@m-schoettel, @ekobastiawan, @aditiagunawan, @lubint, @andreaacri : 

I have just changed the file name for Tim's and my Svayambhu edition to respect the rules laid down in the project's File Naming Conventions [https://github.com/erc-dharma/project-documentation/blob/master/guides/FNC/DHARMA_FNC_v01.1.pdf](https://github.com/erc-dharma/project-documentation/blob/master/guides/FNC/DHARMA_FNC_v01.1.pdf).

Please change the file names for critical editions following the model for Svayambhu, now called `DHARMA_CritEdSvayambhu.xml`, and please rename the files for diplomatic editions following the rules formulated in FNC §1.3, §1.6 and §2.

Remember also to change the relevant `<idno>`, as in `<idno type="filename">DHARMA_CritEdSvayambhu</idno>`. Then push the revised file(s) to the repository, and respond to this thread with a brief statement that your file(s) is (or are) done.

@ajaniak @alevivier : it would be useful to add examples of CritEd and DiplEd filenames in §2.5 in a next version of the FNC.

Thanks!

Arlo

**Comment by aditiagunawan** [comment]
Dear Arlo,

It is done. Thank you. Please check !

Best,
Aditia

**Comment by m-schoettel** [comment]
It is done with my editions as well (274d577).

**Comment by andreaacri** [comment]
done at my end as well.

**Comment by lubint** [comment]
Done.
Best,
Tim

From: arlogriffiths ***@***.***>
Reply-To: erc-dharma/tfd-nusantara-philology ***@***.***>
Date: Saturday, April 3, 2021 at 3:42 AM
To: erc-dharma/tfd-nusantara-philology ***@***.***>
Cc: "Lubin, Tim" ***@***.***>, Assign ***@***.***>
Subject: [erc-dharma/tfd-nusantara-philology] change filenames (#23)


@m-schoettel<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fm-schoettel&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494113377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kJ0uFlH5Rl3wCi0x5KWoRAss3wbVRsY7fkLuApfroCc%3D&reserved=0>, @ekobastiawan<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fekobastiawan&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494253292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rZAkgS9rtEBq1voWxhtEBYF9Ox0iszMdByXbT8%2BFOhY%3D&reserved=0>, @aditiagunawan<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faditiagunawan&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494263288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A8ayYI07pi0ELsRgVrp14RFuWbBvfqM6CPVbT%2BflzVE%3D&reserved=0>, @lubint<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flubint&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494263288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p0p5GrQsHLOjRPmhb739D0dg7bnkkK0Cy0Ij8ObO71k%3D&reserved=0>, @andreaacri<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandreaacri&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494273282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bo5fUXL3%2FMvY3WpDzwxOLa9nBgy52010COqLCjwF2zk%3D&reserved=0> :

I have just changed the file name for Tim's and my Svayambhu edition to respect the rules laid down in the project's File Naming Conventions https://github.com/erc-dharma/project-documentation/blob/master/guides/FNC/DHARMA_FNC_v01.1.pdf<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ferc-dharma%2Fproject-documentation%2Fblob%2Fmaster%2Fguides%2FFNC%2FDHARMA_FNC_v01.1.pdf&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494273282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HtJhqSBM%2Frn5m0gZaD%2FbPSdNNqSreh9jq6%2BifXhd6qc%3D&reserved=0>.

Please change the file names for critical editions following the model for Svayambhu, now called DHARMA_CritEdSvayambhu.xml, and please rename the files for diplomatic editions following the rules formulated in FNC §1.3, §1.6 and §2.

Remember also to change the relevant <idno>, as in <idno type="filename">DHARMA_CritEdSvayambhu</idno>. Then push the revised file(s) to the repository, and respond to this thread with a brief statement that your file(s) is (or are) done.

@ajaniak<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fajaniak&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494283276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Rm0oqJ8wSRvDpJMXLWqDyhnaSXf86%2Fg05zk1Xh3c6mk%3D&reserved=0> @alevivier<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falevivier&data=04%7C01%7Clubint%40wlu.edu%7Ce9ce97cde751483b62ad08d8f674064d%7Cd1a80622a99943e58eb67873905e939e%7C1%7C1%7C637530325494283276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6YwZzpQsw9AnSRE5QzI4us%2Bk3%2Fali3iXRLxIiwOfLAA%3D&reserved=0> : it would be useful to add examples of CritEd and DiplEd filenames in §2.5 in a next version of the FNC.

Thanks!

Arlo

**Comment by arlogriffiths** [comment]
Thanks a lot Aditia, Andrea, Marine and Tim for your quick action.

@alevivier @ajaniak — please close this once you have taken note of my suggestion to add examples to the FNC.

**Comment by ajaniak** [comment]
OK
