### ISSUE TITLE
grouping first two <l> and last two <l> together on a single line in display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#24]
Dear @ajaniak — as discussed yesterday, please apply a rule for display of `<lg>` that pairs of `<l>` must be displayed in a single line if `met="anuṣṭubh"`.

I have made the necessary changes in the file DHARMA_CritEdSvayambhu.xml so we can use it to test the rule.

**Comment by ajaniak** [comment]
It has been done

**Comment by arlogriffiths** [comment]
thanks!
