### ISSUE TITLE
siglum to be included in display of <pb ed="..." n="..."/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#25]
- example code `<div><ab type="invocation" xml:lang="san-Latn"><pb ed="#L" n="1"/><pb ed="#K" n="1v"/>//0// avighnam astu //0//</ab>`

- present display:
<img width="267" alt="Capture d’écran 2021-04-08 à 12 35 35" src="https://user-images.githubusercontent.com/835603/114012683-f043e680-9866-11eb-83da-a04cc27e1961.png">

- could we have a display like [L1][K1v] for `<pb ed="#L" n="1"/><pb ed="#K" n="1v"/>`?

Thanks!

**Comment by ajaniak** [comment]
The current display shows the siglum inside a tooltip, I suppose you want it to disappear in favor of only a textual display, is that it? 
Note that the attribute you should use is `@edRef` and not` @ed`, that's why the display provides only the content of `@n`.

**Comment by arlogriffiths** [comment]
Thanks for pointing out that @ed needed to be replaced by @edRef. I now see the you mention:

<img width="310" alt="Capture d’écran 2021-04-08 à 15 13 38" src="https://user-images.githubusercontent.com/835603/114032884-0c528280-987d-11eb-9446-9412df2c9825.png">

Since such use of `<pb/>` will not havce a high frequency in our editions, and most sigla will not occupy much place, I think indeed it is preferable to have a purely textual display.

**Comment by ajaniak** [comment]
Ok it is done.

**Comment by arlogriffiths** [comment]
Thanks. The formatting of the sigla still seems a bit different than that if the surrounding brackets and value of @n. See screenshot:

<img width="309" alt="Capture d’écran 2021-04-08 à 17 04 54" src="https://user-images.githubusercontent.com/835603/114050578-aec63200-988c-11eb-8294-a3a7f37d1a23.png">

Can you apply the same formatting to the whole string from [ to ]?

**Comment by ajaniak** [comment]
I have added a new css already but it requires some time to be applied.

**Comment by arlogriffiths** [comment]
The CSS did work for a while, but at the moment I see this:

<img width="288" alt="Capture d’écran 2021-04-15 à 05 47 47" src="https://user-images.githubusercontent.com/835603/114811286-22e16800-9dae-11eb-95cc-fa3d573fcda1.png">

**Comment by ajaniak** [comment]
It has nothing to do with the encoding. Your encoding is `<pb ed="#L" n="1"/><pb ed="#K" n="1v"/>`, you need to use the correct attribute @edRef.

**Comment by arlogriffiths** [comment]
ah yes, thanks for reminding me about that once again.

I have had some previously made edits vanish, apparently because I had the file open both in Oxygen and in Atom and wasn't paying attention to where I made edits and when I need to commit the edits.
