### ISSUE TITLE
display of <app> in case of <supplied>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#26]
- there is a conflict between the use of colors for `<supplied>` and `<lem>` within `<app>`

- example code from Svayambhu

`<quote><supplied>
...
<lg met="anuṣṭubh">
	<l>strīpuṁdharmo vibhāgaś ca</l> <l>dyūtam <app><lem source="#Svayambhu">āhvānam uvāca</lem><rdg wit="bib:Olivelle2005_01">āhvaya eva ca</rdg></app> |</l>
	<l>padāny aṣṭādaśaitāni</l> <l>vyavahārasthitāv iha ||</l>
</lg>
    <note type="parallels">
        <list>
          <item sameAs="MDhŚ08.007"/>
        </list>
  </note>
</quote></supplied>`

- display:

<img width="772" alt="Capture d’écran 2021-04-08 à 12 52 56" src="https://user-images.githubusercontent.com/835603/114014929-719c7880-9869-11eb-9335-c9ca75912c10.png">

- as solution, could you let the red of `<app>` overrule the grey of `<supplied>` but revert to grey after the `<app>` is finished?
- can you prevent the appearance of `<app>` in `<supplied>` disturbing the normal layout of `<lg>` and display of `<app>` number?

**Comment by ajaniak** [comment]
It should be good. Now can you check if it is what you meant.

**Comment by arlogriffiths** [comment]
Thanks. Yes, it looks good now.

I am presuming that the fact that the note numbers have shifted to the left margin in the current display is temporary and unrelated to the present issue. Please simply close this issue if my presumption is correct.
