### ISSUE TITLE
Validation on diplomatic edition

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#27]
Dear @ajaniak 

I find a problem on the validation of diplomatic edition. It seems related to page numbering `<fw type="pageNum" place="left margin" n="2v">` and deletion by the scriber `<del rend="strike-out">`. Is there any adjustment of the template or is there a new rules in Encoding guidelines? 

Best,
Aditia

**Comment by ajaniak** [comment]
Dear @aditiagunawan, 

Nothing has changed, but previously there wasn't any validation of the files of Diplomatic edition. The rules are the one from the EGD. 
The value is `strikeout` and not `strike-out` for the element `<del>`. 
The possible values haven't change and are still for `@place` on `<fw>`:  top-left, top, top-right, left, right, bot-left, bottom, bot-right. Note also that the `@type="pageNum"` isn't allowed, see EGD 3.3.5

Best, 
Axelle

**Comment by aditiagunawan** [comment]
Dear @ajaniak 

Thank you. I made changes in encoding, so it works now. But I still have one left notification `Document has been marked not available: https://raw.githubusercontent.com/erc-dharma/project-documentation/master/DHARMA_IdListMembers_v01.xml`. What this does mean? 

Best,
Aditia

**Comment by arlogriffiths** [comment]
That problem should go away if you press the validation button. See screenshot.

<img width="243" alt="Capture d’écran 2021-05-31 à 11 45 38" src="https://user-images.githubusercontent.com/835603/120174784-c7582600-c205-11eb-81ec-2a4e0a320876.png">

**Comment by aditiagunawan** [comment]
Thanks @arlogriffiths It works now. 

Best,
Aditia
