### ISSUE TITLE
DHARMA_CritEdSasanaMahaguru.xml: version conflict

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#29]
Dear all, 

Could you check the version conflict happening in  `DHARMA_CritEdSasanaMahaguru.xml` and try to resolve it please? 

Thanks
Best,

**Comment by aditiagunawan** [comment]
Dear Axelle,

The file has been resolved. I don't know why it can happen actually. 

Best,
Aditia

**Comment by ajaniak** [comment]
Great, thanks! Probably you have forgotten to git pull once.
