### ISSUE TITLE
<witDetail type="ac"/ or "pc"/> in <lem> doesn't appear in the transformation

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#30]
Dear @ajaniak 

I have this encoding:

`<app><lem wit="#A #EdASD">landuh</lem><witDetail wit="#EdASD" type="ac"/><rdg wit="#B">ladaḥ</rdg><rdg wit="#EdASD">landuṅ</rdg><witDetail wit="#EdASD" type="pc"/></app>`

And in the transformation it appears like this:
<img width="253" alt="Screenshot 2021-10-08 at 21 07 23" src="https://user-images.githubusercontent.com/55530631/136612964-f4a360ba-3bd4-467c-9da1-388b3a86cf3b.png">

I wonder whether we can display `<witDetail type="ac"/>` in `<lem>` as we can have in `<rdg>`, so the transformation of this encoding would be like _landuh_ **A** **EdASDac**? 

Best,
Aditia

**Comment by ajaniak** [comment]
This has been done 
<img width="265" alt="Capture d’écran 2022-04-01 à 14 07 07" src="https://user-images.githubusercontent.com/33328906/161260229-4afebafd-8585-4616-83b4-0b0413723605.png">
