### ISSUE TITLE
new font to be applied in titles, headings, appafrarus, sigla

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#31]
@ajaniak : now that we are using a new font in the display of editions, can we also deploy it in all contexts, such as titles, section headings, apparatus display, sigla? see screenshots showing some contexts where the new font is not yet implemented. thanks!

<img width="846" alt="Capture d’écran 2021-10-08 à 20 57 24" src="https://user-images.githubusercontent.com/835603/136618423-397a74f2-0601-440c-b55c-1221a8989aff.png">
<img width="388" alt="Capture d’écran 2021-10-08 à 20 57 43" src="https://user-images.githubusercontent.com/835603/136618431-0622ef63-00b8-4c29-b4fb-78354fa6aaed.png">
<img width="711" alt="Capture d’écran 2021-10-08 à 20 58 50" src="https://user-images.githubusercontent.com/835603/136618433-4ec2b00d-b9b7-46bd-867c-40f3c23eb1f4.png">

**Comment by ajaniak** [comment]
I have changed the system to force the font to be applied using cdn deliver. It will require an effective internet connexion though. I have chosen IndUni-H, let me know if you prefer something else.
