### ISSUE TITLE
display of <lem> for <app> wrapped around other <app>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#32]
Dear Axelle,

Please see screenshot:

<img width="1179" alt="Capture d’écran 2021-10-10 à 18 39 11" src="https://user-images.githubusercontent.com/835603/136707219-ef52d9ea-47bc-4301-b9b9-d9f5f0458abf.png">

Is it possible not to display the note numbers with in the display of `<lem>` in such a case? Thanks!

**Comment by arlogriffiths** [comment]
not yet perfect, as the wrapped `<app>` are now not visible at all. see how (51) ands (52) are missing in the screenshot:

<img width="882" alt="Capture d’écran 2021-10-13 à 11 30 29" src="https://user-images.githubusercontent.com/835603/137116770-ec9bd42d-ed6e-4f25-ba4b-26aea8384142.png">


by the way, do you understand what's causing the unwanted space before the comma right after _vetanasya na ca dānam_?

**Comment by ajaniak** [comment]
Your lastest comment should be resolved in the next transformation

**Comment by arlogriffiths** [comment]
great, thanks. so now only the numbering around App 50 remains to be solved.

**Comment by ajaniak** [comment]
It is a structural issue, so I have move the display to generate the app number before creating the lemma string. It should be resolving this without impact on the main display, even if the issue on app entry generated when app are embedded is still unresolved

**Comment by ajaniak** [comment]
In theory, all the issues listed here are now resolved, especially, app number being generated in the tooltip lem when it is the ancestor of another lem. 
However, the result should be checked and validated

**Comment by arlogriffiths** [comment]
looks good to me. shall we close this, simply wait and see if we find related problems elsewhere, and if so create new issues? if you'd prefer to check/validate before closing this, can you help point me to other relevant parts of Svayambhu or other files where related phenomena occur, so I can check the display?

**Comment by ajaniak** [comment]
Great. Basically, I have reworked all the apparatus code to generate it in the text: we need to check the order of the entries and behaviour for the "exotic" one which are not made from `<app>`. 
 All the highlight functions still need to be reworked and I have already identify issues about the fake lemma making in the context of stanzas. 
 We can go issue by issue, it might be easier.
