### ISSUE TITLE
display of stanza numbers, of @met and @real

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#34]
@ajaniak — could we add the basic of layout of verse texts to our display code?

For code like this
`<div type="canto" n="1" met="jagaddhita" real="+++--+-+---+------+-+-+">`

I expect a kind of header looking like this

**Canto 1.
      Jagaddhita: – – – ⏑ ⏑ – ⏑ – ⏑ ⏑ ⏑ – ⏑ ⏑ ⏑ ⏑ ⏑ ⏑ – ⏑ – ⏑ –**

If you approve of this use of @real, then we need to add it to EGD. If not, we need another solution to display the metrical pattern.

Finally, every stanza should show a double number, one for the canto and one for the stanza numbe, like "1.1", etc., in the left margin.

**Comment by ajaniak** [comment]
A first display has been made

**Comment by arlogriffiths** [comment]
Thanks. Got it now.

I like it. But can the code display + and - as  the metrical symbols – and ⏑ and insert a space between every symbol?

**Comment by ajaniak** [comment]
This has been done. 
<img width="604" alt="Capture d’écran 2022-04-01 à 14 05 45" src="https://user-images.githubusercontent.com/33328906/161260016-9504eabd-9e25-47b3-8011-284b3ef5ba0f.png">
