### ISSUE TITLE
how to encode a <div> which is not of @type="dyad"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#37]
Can I simply remove the attribute @type from the following `<div>`?

```
<div type="dyad" n="1">
				<p>bhagavān vararuci mupulakən sāra-sāra saṅ hyaṅ aṣṭādaśaparva, gave bhagavān byāsa, mataṅnyan panamaskāra sira i bhagavān byāsa, liṅnira,</p>
			</div>
```

I don't find EGC 3.2 clear on what do to with non-dyad paragraphs in case of texts mostly structured in dyad. Can you propose a modification in the gdoc?

**Comment by ajaniak** [comment]
If you remove the attribute `@type="dyad"`, I will need another value in order to stabilize the display and the different numbering pattern.

**Comment by arlogriffiths** [comment]
Yes, that's what I expected. May I suggest we add two values for @type, namely "prose" and "verse" to be used in editions of texts which predominantly use other types, whenever there is a prose paragraph or a verse forming a div that does not belong to the predominant category? If you agree, can you propose the necessary additions in EGC?

**Comment by ajaniak** [comment]
In that case, I will see if I can find a way to work without adding the attribute `@type`.

**Comment by arlogriffiths** [comment]
Before you do a lot of work, let me say that I wouldn't have a great objection applying `<div @type="dyad">` even around such a `<p>` which is not part of a dyad.

Another solution could be to include the `<p>` at the start of the next dyad.

And yet another soplution could be to come up with another value for @type, like "liminal", as I suppose this kind of paragraph is ,most likely to occur at the beginning or end of a text structured in dyads.

Please advise on what is least work for you and most satisfactory from a semantic/TEI point of view.

**Comment by ajaniak** [comment]
For now, I was able to stabilize the display without  `@type="dyad"`. We will have to be careful to that the display is stable in all circonstances, but it seems ok during the few tests I have made. It means, you can keep the `<div>` neutral around the element `<p>`.  

I think you should only add a `<p>` in the previous or next dyad following the same rules we have stated in the base-text section (though, we might need to review them now that the guide is more advanced)

Regarding the value "liminal" it might be a great idea to add it in the values. it can be helpful for some encoders.
