### ISSUE TITLE
fix required in display of @n of <lg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#38]
The number of stanza 1 should be placed in the same position as tjhe number of stanza 2 in the example below:

<img width="867" alt="Capture d’écran 2021-11-17 à 11 31 52" src="https://user-images.githubusercontent.com/835603/142184381-759f2f3d-bdcb-4d17-952d-cd30e3fc5d4b.png">

**Comment by ajaniak** [comment]
I don't see any issue
<img width="755" alt="Capture d’écran 2021-11-17 à 12 29 32" src="https://user-images.githubusercontent.com/33328906/142192608-c46941ab-91d5-417d-b6ec-498ef98b4b73.png">

**Comment by arlogriffiths** [comment]
could it be a browser issue? if I view on firefox, the number "1" is placed on the next line, as in the example above.

if I view on Chrome, the display of the stanza is like this, with irregular arrangement of `<l>`s:

<img width="655" alt="Capture d’écran 2021-11-17 à 12 42 43" src="https://user-images.githubusercontent.com/835603/142194428-cffa9fcb-e850-484b-98d3-0606c1c497a9.png">

I also notice varying behavior between Firefox and Chrome for the `<listWit>`.

**Firefox**
<img width="641" alt="Capture d’écran 2021-11-17 à 12 44 25" src="https://user-images.githubusercontent.com/835603/142194611-ce685fa7-43fa-4189-8cd3-1bef740df6f6.png">

**Chrome**
<img width="1028" alt="Capture d’écran 2021-11-17 à 12 44 59" src="https://user-images.githubusercontent.com/835603/142194700-04ab00a4-8840-4b78-802d-33e49a5561ba.png">

**Comment by ajaniak** [comment]
It should be good for both points now
