### ISSUE TITLE
fixes for encoding and display of author and title

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#39]
1. Please add @type="alt" to the possible values for `<title>`, as we discussed recently. At the moment, it is still not allowed.

<img width="601" alt="Capture d’écran 2021-11-20 à 16 31 09" src="https://user-images.githubusercontent.com/835603/142732063-f18d4132-a982-49aa-af4c-60353d332020.png">

2. Please modify the arrangement of the various `<title>` elements, any `<author>` and  any `<editor>` so that, once the first request is dealt with, we'd get a display like this:

The _Sārasamuccaya_ or ‘Essential Anthology’
by Vararuci 
Digital Critical Edition of an Anthology of Sanskrit Stanza on _dharma_ with Old Javanese Paraphrase
edited by Arlo Griffiths

**Comment by ajaniak** [comment]
`alt` has been added in the schema last tuesday. 

The rest has been updated

**Comment by arlogriffiths** [comment]
thanks. I am still getting an error message as you can see:

<img width="1176" alt="Capture d’écran 2021-11-22 à 12 14 04" src="https://user-images.githubusercontent.com/835603/142851903-a25ed666-0c65-46bd-ac80-3231e639f09e.png">

**Comment by ajaniak** [comment]
Tu dois appuyer sur le bouton de validation pour monter le nouveau schéma dans ton système, tu as des problèmes de connexion et tu valides sur la mémoire cache au lieu d'appeler le nouveau schéma par défaut.

**Comment by arlogriffiths** [comment]
merci, c'est bon maintenant.

bêtise de ma part: je pensais l'avoir fait mais c'était le bouton formatage sur lequel j'avais appuyé.
