### ISSUE TITLE
spacefiller or filler

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#4]
Dear @erc-dharma/nusantara-philology, 

You have two values for `<g>/@type`: spacefiller and filler. Is there a difference between the 2? 

Best,

**Comment by arlogriffiths** [comment]
it should be the same @type in every instance.

Le 14 avr. 2020 à 11:23, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Dear @erc-dharma/nusantara-philology<https://github.com/orgs/erc-dharma/teams/nusantara-philology>,

You have two values for <g>/@type: spacefiller and filler. Is there a difference between the 2?

Best,

**Comment by aditiagunawan** [comment]
As far as I remember, I use "filler" instead of "spacefiller", as indicated in EG 4.2.

**Comment by m-schoettel** [comment]
It seems I use exclusively the attribute filler in my file.

**Comment by ajaniak** [comment]
I made the change, the file concerns is Astadasa which seems to be a test of some sort. If not relevant anymore, maybe you could create an archives folder.
