### ISSUE TITLE
help with changing values of @n in one file

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#40]
dans DHARMA_CritEdSarasamuccayaVararuci.xml, à partir de `<div type="dyad" n="63">`, pourrais-tu diminuer par 1 toutes les valeurs des `<div type="dyad" n="...">`?

il est temps que je commence à apprendre comment me servir de xpath ou autres outils pour devenir plus autonome dans ces matières somme toute facile. si tu as un créneau pour commencer à m'initier...

**Comment by ajaniak** [comment]
It is done. The use Xpath inside of an XSLT to do this, not Xpath alone.
