### ISSUE TITLE
@n on the <p>

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#41]
Hello @ajaniak ! I see that the attributes @n on the `<p>`s in my file DHARMA_CritEdSiksaKandangKaresian are now preventing the file to be validated. If I should no longer use @n, could you make the necessary global changes in my file? Thanks!

**Comment by ajaniak** [comment]
Dear @aditiagunawan, 

Encoding @n on `<p>` where never allowed, see p. 32 of the guide. 
Manuscripts don't have any schema yet and I have only starting working on them. 

It is done
