### ISSUE TITLE
display of <supplied reason="omitted"><lg>...</lg></supplied>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#42]
@ajaniak — is it possible to make space after the opening angle bracket symmetrical to the space that we have before the closing one? see current display here:

<img width="635" alt="Capture d’écran 2021-11-25 à 07 34 52" src="https://user-images.githubusercontent.com/835603/143392040-2fa2fd2b-ed55-4692-b5a6-4532daf98087.png">

**Comment by ajaniak** [comment]
It should be good, but it can take up to 24 hours to be effective.

**Comment by arlogriffiths** [comment]
now the brackets around that stanza have completely disappeared. that wasn't my intention...

**Comment by ajaniak** [comment]
The update on the server isn't available yet.

**Comment by arlogriffiths** [comment]
Again a difference between two browsers.

1. current display on Firefox: **no brackets at all**
<img width="594" alt="Capture d’écran 2021-11-27 à 11 28 47" src="https://user-images.githubusercontent.com/835603/143677545-70bdc319-d05f-477d-bcda-581a8d26f4b9.png">

2. current display on Chrome: **brackets but not yet fully symmetrical**
<img width="597" alt="Capture d’écran 2021-11-27 à 11 29 09" src="https://user-images.githubusercontent.com/835603/143677548-dd88da62-6861-4c44-96bc-92bbf2b8baea.png">

**Comment by ajaniak** [comment]
I have the same view in both browsers. I am not sure to understand what you mean by "fully symmetrical"

**Comment by arlogriffiths** [comment]
Thanks, now I also see the brackets on Firefox. 

Regarding symmetry, I meant that there a space seems to be inserted before the closing ⟩ while there is none after the opening ⟨. No space should be inserted by display  `<supplied>`.
