### ISSUE TITLE
copyability of <supplied> brackets

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#43]
I notice that when I try to copy/paste from a paragraph like this, the ⟨...⟩ brackets for `<supplied>` disappear.

<img width="536" alt="Capture d’écran 2021-11-30 à 15 43 47" src="https://user-images.githubusercontent.com/835603/144068404-b6ea73a2-4340-481f-a0d7-2fafeca24129.png">

Is it possible to embed them firmly into the underlying text, so they don't get lost after copy-paste?

**Comment by ajaniak** [comment]
It has been done as well
