### ISSUE TITLE
color on closing bracket?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#44]
@ajaniak — Why is the second bracket in the rdg not of the same color as the first, in this example?
<img width="411" alt="Capture d’écran 2021-12-06 à 15 06 23" src="https://user-images.githubusercontent.com/835603/144860390-71f0e264-6661-495a-8cf0-ea7abbf102d9.png">

**Comment by ajaniak** [comment]
I have updated the code. It can take a little time to be updated on the files though.

**Comment by ajaniak** [comment]
<img width="276" alt="Capture d’écran 2022-04-01 à 14 00 00" src="https://user-images.githubusercontent.com/33328906/161259213-0abec2be-d070-4296-b45a-e72d66333bb0.png">
Done
