### ISSUE TITLE
implement jumping to specific divs of a text in display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#45]
Can we implement a way to jump immediately to a specific place in the display of a text edition, or at least jumping to specific chapter/canto beginnings? Something like the document outline in a googledoc...

**Comment by ajaniak** [comment]
It is added, but it requires the addition of `@xml:id`, see your edition of the Svayambhu. 
I have put it in bold and add the behaviour set up for links so far, but it can be updated as you see fit. 
The textual content to anchor the link to appear is made with the `@type`, when available, or the name of the element otherwise, and with `@n`, again when available, e.g for div91, the display will be: **dyad 91**.

**Comment by arlogriffiths** [comment]
I don't see the implementation yet. Can you send a screenshot of what you are talking about?

**Comment by ajaniak** [comment]
See note 435 with the dyad 91, if you click on it, you will go to the said dyad. 

![Capture d’écran 2021-12-14 à 16 34 25](https://user-images.githubusercontent.com/33328906/146029234-8eb590ef-c078-4bfb-9608-f45bfa9068dd.png)

**Comment by arlogriffiths** [comment]
Thanks. That new feature is useful, but it is not what I meant. I meant something that is constanrly visible in the user's screen and allows jumping randomly to any div. I referred to the document outline in a googledoc, as in this screenshot:

<img width="1111" alt="Capture d’écran 2021-12-15 à 06 06 38" src="https://user-images.githubusercontent.com/835603/146126849-796b149e-e9b2-46b5-9f4c-62c03dc4f5f2.png">

But I suppose bootstrap offers solutions which look a bit different.

**Comment by ajaniak** [comment]
Ah I see what you want now.

**Comment by ajaniak** [comment]
I have added a first draft. It uses css and js so it may take some time to be uploaded.

**Comment by arlogriffiths** [comment]
Thanks. It's functional now, and looks good for the time being. Here's a screenshot.

<img width="1147" alt="Capture d’écran 2021-12-17 à 06 38 36" src="https://user-images.githubusercontent.com/835603/146494864-b1082f9a-ceae-4119-97f9-741e901cf1b7.png">

If it's easy, could you replace "Toggle Table of Contents" by "Document Outline" and is it possible to indent the `<div>`s in the outline based on their structural position, the child `<div>s` with more indent than the parent `<div>`s?

**Comment by arlogriffiths** [comment]
Now I notice that there is a discrepancy between 

1. the display on mobile phone and when the local file is displayed: in those cases, the display is as you presumably intended it, and as shown in my screenshot above.
2. the display if an html is displayed via https://erc-dharma.github.io/tfd-nusantara-philology/output/critical-edition: that case (on Firefox at least), the table of contents is only shown at the very top of the display, and not in the left margin of the edition, which comes much lower — along with the ToC button. See screenshots.

Can this be solved?

<img width="1402" alt="Capture d’écran 2021-12-17 à 07 01 38" src="https://user-images.githubusercontent.com/835603/146496955-3d97b117-a5a3-4031-9184-aff2aa377bac.png">

<img width="1525" alt="Capture d’écran 2021-12-17 à 07 02 35" src="https://user-images.githubusercontent.com/835603/146497114-eea13209-4b03-4bce-8bd3-cdb52b07ef0a.png">

**Comment by ajaniak** [comment]
It have changed the name and added a sort of hierarchy, but it might need to be updated at some point depending on the structure applied on the editions. 
It seems firefox take longer to apply the changes. But to accommodate, some of techs differences between the web browser, I have updated and moved some contents around.

**Comment by arlogriffiths** [comment]
Thanks a lot. It looks wonderful. Closing this issue. Will open a new one if further fine tuning becomes necessary.
