### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#46]
I don't understand this error message:

<img width="1478" alt="Capture d’écran 2021-12-14 à 16 10 57" src="https://user-images.githubusercontent.com/835603/146025366-44187986-49cb-4c89-9202-7fb101d1b118.png">

A problem in the schema?

**Comment by arlogriffiths** [comment]
When validating on Oxygen, I get the follow error messages:

<img width="1393" alt="Capture d’écran 2021-12-15 à 05 59 53" src="https://user-images.githubusercontent.com/835603/146126179-32836107-5081-4698-b613-e49dbbf0c80d.png">

I have now resolved the first encoding error. The others don't seem related to the error message I sent yesterday. Reopening the file on Atom, linter gives me 346 error messages, mostly or all related to the new xml:ids:

<img width="1504" alt="Capture d’écran 2021-12-15 à 06 03 37" src="https://user-images.githubusercontent.com/835603/146126558-7f9b1d18-adb3-4ded-b83b-6b5d6ff382d8.png">

**Comment by ajaniak** [comment]
The validation errors you have in Oxygen are expected. 
However with Atom, you are working with an older version of the schema. Have you close your file or the application to relaunch it recently? You need to do so to reset the cash memory used to validate.

**Comment by arlogriffiths** [comment]
thanks. that has solved the problem!
