### ISSUE TITLE
matching translations to paragraphs of edition

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#47]
@aditiagunawan — please describe the structural problem you mentioned yesterday. Is it a problem of how to encode paragraphs of translation, or is a question of display, or both?

**Comment by aditiagunawan** [comment]
@arlogriffiths - My question is how to Identifying correspondence between <div> and <p>. If we look at the Svayambhu example in EGC 9.1.3, `<p>` is associated with xml:id of a `<div>` on CritEd (so we have `<p n="1" corresp="#svayambhu-02.01">`), not xml:id of <p> in CritEd (so not `<p n="1" corresp="#svayambhu-02.01.01">`. I see the HTML display for the translation button only has one per `<div chapter>`. Will this not be a problem for chapters consisting of more than one `<p>`?

**Comment by ajaniak** [comment]
I made this example in the svayambhu, since I didn't know which part it was matching, i choose the higher one. For now, the display is based on the higher level, since I don't any translation to work with

**Comment by arlogriffiths** [comment]
Aditia has given a little bit of contents to his file DHARMA_CritEdSiksaKandangKaresian_transEng01. He can give more if that will be useful for testing purposes, but he will need your guidance on what to do with `xml:id="SKK-01-01"` etc.

**Comment by ajaniak** [comment]
@aditiagunawan 
I have update the main `@xml:id`of your edition to `skk`. The ids should be provided in the main edition, I have added them a few days ago to allow the display of the document outline on the side.  Translation only used the attribute `@corresp` to align the paragraphs given in the translation with the ids given in the edition, and don't use ids to identify its component. To fill them, add an hashtag and then the id of the part, you are translating. 

I have rewritten the attributes of the first paragraph in DHARMA_CritEdSiksaKandangKaresian_transEng01 to show you how it works. You can also use the section related to translation in the encoding guide: §9.1, the content are closed to the EGD, except for the parallelism between the files. 

Let me know if you have question or facing issues.

**Comment by aditiagunawan** [comment]
@ajaniak 
Thank you. I try to apply the same outline for the next three paragraphs. Please check my file and see if that is the correct way to correspond the translation to the main edition. I see that the transformation is work with the first paragraph but not (or should wait for moment?) with the next paragraphs. 



Thank you.

**Comment by aditiagunawan** [comment]
@ajaniak It works and I like it a lot! Thank you Axelle.
