### ISSUE TITLE
error message concerning <date>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#49]
See below. The "description" seems to be incomplete.

How should I solve this error?

<img width="1448" alt="Capture d’écran 2022-01-05 à 05 54 33" src="https://user-images.githubusercontent.com/835603/148162647-f0bd7a71-d61c-4e27-8983-365caa218f37.png">

**Comment by ajaniak** [comment]
I have resolved the issue in the schemas
