### ISSUE TITLE
problem with @type on <g>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#50]
as per EGD 4.2.5 (gdoc version), I wish to use `<g type="squiggleVertical">§</g>` in a diplomatic citation of a `<rdg>`, but the schema protests:

<img width="1464" alt="Capture d’écran 2022-01-05 à 15 32 31" src="https://user-images.githubusercontent.com/835603/148234670-3c66c897-4036-465a-8643-79d18682bfba.png">

I think this is a difference between the latest release of the EGD and the rule that is stated in the gdoc for the next release. It is a good idea to  update the schema on this point already now, or should I use @type="filler" on `<g>` as long as the new EGD has not been released?

**Comment by ajaniak** [comment]
I have opened the list of values for the @type on `<g/>`.

**Comment by arlogriffiths** [comment]
for the moment, the value "squiggleVertical" still causes the file to be invalidated

**Comment by ajaniak** [comment]
Have you reset your schema by relaunching the app or by validating manually?

**Comment by arlogriffiths** [comment]
ah, thanks — didn't realize that was necesary! problem solved.
