### ISSUE TITLE
EGC §4 and §6.2.5

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#51]
regarding the issue of how to encode base-text which is implied but unknown, I would like something which allows us to get a display that is slightly more sophisticated than this:

<img width="849" alt="Capture d’écran 2022-01-05 à 18 14 06" src="https://user-images.githubusercontent.com/835603/148260219-3f47dce1-7e4d-48c3-97f1-9f3151a6c5af.png">

because actually nothing is supplied, and nothing can be supplied even though we would like to if only we knew what it was. is there any attribute we can offer for encoding on the `<note>` in `<listApp type="parallels">` or on `<supplied reason="subaudible">` to get a display like "Text to be supplied unknown to editor."?

**Comment by ajaniak** [comment]
Is it what you want? 
<img width="881" alt="Capture d’écran 2022-01-06 à 11 49 50" src="https://user-images.githubusercontent.com/33328906/148371580-72cfd3c4-c890-4d55-8212-abd67113e327.png">

**Comment by arlogriffiths** [comment]
that could be one option, or only [] with a pop-up giving the message [Text to be supplied unknown to editor], following the system we have been using so far, as shown in my screenshot above. could we generate it by encoding `<supplied reason="subaudible" type="unknown">`?

**Comment by ajaniak** [comment]
No you can't add `@type` to `<supplied>`, the element itself being already define semantically. If you want `@type="unknown"`, you need to put it on `<note>`. 
```
<ab xml:id="svayambhu_08.05.01"><supplied reason="subaudible">
     <listApp type="parallels">
          <app>
     <note type="unknown"/>
          </app>
    </listApp>
   </supplied></ab>
```
Another solution would be to delete all the structure and to keep only the `<note>` or use another element altogether such an empty element which I don't like as solution. 

Finally, another solution could be to delete the `<ab>`, the `<supplied>` and `<listApp>` and using `@type` or `@subtype`directly on the `<div>`. II might not be really practical though for cases such as dyad 16, but regarding only TEI, but it is the only solution that isn't wrong in terms of structuring.

**Comment by arlogriffiths** [comment]
I would prefer not to meddle with our structure, and it seems much more intuitive to put an attribute on `<supplied>` than on `<note>`. can we use another attribute than @type? or can we use a different value for @reason? e.g., can we replace "subaudible" by another, more specific value, like "subaudible-unknown"? or could we use "implied" here? (I must confess I don't  remember well what, if any, distinction we have tried to make between "implied" and "subaudible", and I haven't looked it up.)

**Comment by ajaniak** [comment]
In theory,  "implied" is to be used for the edition and "subaudible"  only for translations. 
Since supplied isn't used to do such a thing, so there is not other attribute. If you want to keep `@reason` why not keep it simple and just add "unknown" rather than making it complicated as "subaudible-unknown".
