### ISSUE TITLE
<hi rend="subscript"> is not working for autogenerated <rdg>s

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#53]
In lines 277-278 of the file DHARMA_CritEdCandrakirana.xml, two witness undergo `<lacunaStart>`. in the apparatus entries that follow, their sigla are not correctly displayed. See screenshot:

<img width="270" alt="Capture d’écran 2022-03-22 à 10 36 38" src="https://user-images.githubusercontent.com/835603/159451236-58763339-7eb6-4d45-972b-8e6d8e55410b.png">

**Comment by arlogriffiths** [comment]
the two "lac. J." items should be differentiated by 1 and 3 in subscript, as defined in the teiHeader on the `<abbr>` for #msja and #msjc.

**Comment by arlogriffiths** [comment]
I see that the ver first apparatus entry generated by the two `<lacunaStart>`s shows the sigla correctly:

<img width="377" alt="Capture d’écran 2022-03-22 à 10 42 37" src="https://user-images.githubusercontent.com/835603/159452155-23c3dbfa-4780-443b-bb54-804245ef712b.png">

**Comment by ajaniak** [comment]
It will work now. Note that the code might need up to 24 hours to be updated depending on the activity on the servers

**Comment by ajaniak** [comment]
<img width="354" alt="Capture d’écran 2022-04-01 à 13 57 33" src="https://user-images.githubusercontent.com/33328906/161258898-311cb88a-07b4-4948-aabf-b6d5ddd801cb.png">
Done.
