### ISSUE TITLE
typos in schema

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#54]
the typos sutrative and syntatic still need to be corrected

<img width="921" alt="Capture d’écran 2022-03-22 à 12 21 54" src="https://user-images.githubusercontent.com/835603/159470865-bd64c3ab-7863-4c2d-af3c-0081c048c3cb.png">

**Comment by ajaniak** [comment]
I can't find it in the schema. it has been already resolved. You are not validating with the last version

**Comment by arlogriffiths** [comment]
how do I make sure I validate with the latest version?

**Comment by ajaniak** [comment]
Have you restart Atom or Oxygen recently? You can forced the cash updates on oxygen manually but not on Atom, so usually restarting work

**Comment by arlogriffiths** [comment]
thanks for the tip. that solved the problem!
