### ISSUE TITLE
rethinking <div>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#55]
We need to rethink a bit how we instruct editors to encode their files and/or how we display them, in cases if mixed verse and prose. See the screenshot:

<img width="1326" alt="Capture d’écran 2022-03-22 à 12 47 27" src="https://user-images.githubusercontent.com/835603/159475490-d21e7968-23e1-47b7-8082-4abc5c4086bd.png">

The `<div>` here labelled "Canto 2" is actually the first `<div>` that has @type="canto". This is not satisfactory. Do you think the issue is basically at the level of encoding or basically at the level of display?

**Comment by ajaniak** [comment]
I have updated the way cantos are counted to make it independant of the <div> elements structure. However, I think candrakirana's structure should be look at since it hasn't change after the automatic transformation and I am not sure it is relevant.

**Comment by arlogriffiths** [comment]
@ajaniak : is this issue still relevanr, you think?
