### ISSUE TITLE
renumbering cantos/stanzas and xml:ids in DHARMA_CritEdKakavinRamavijayaTaningrat

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#56]
J'ai trouvé une fin de canto qui m'avait échappé jusqu'à présent. Du coup, à partir de `<lg xml:id="rt_30.06" n="6">`, les numérotations ne sont plus bonnes.

Peux-tu les mettre à jour?

Merci!

**Comment by ajaniak** [comment]
Done

**Comment by arlogriffiths** [comment]
thanks!
