### ISSUE TITLE
layout of Candrakirana

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#57]
Something is going wrong with the layout of the Candrakirana in html. See screenshot below: the sreen is much too wide, so one needs to set a very small letter size to be able to to see left and right ends of the screen. This is not happening in the other html displays. Do you understand the cause, Axelle?

<img width="1617" alt="Capture d’écran 2022-04-09 à 07 21 21" src="https://user-images.githubusercontent.com/835603/162557759-bb9b096c-b580-4575-8f2c-2dd9386f6d24.png">

**Comment by arlogriffiths** [comment]
even two days later, the layout is still not as expected. see screenshot. by the way, the display of the colophon isn't as we expect it either. is it the same problem, or is it a different one?

<img width="1427" alt="Capture d’écran 2022-04-14 à 06 21 30" src="https://user-images.githubusercontent.com/835603/163313298-c0da97ed-e40b-448e-9baa-fe9b71e221fb.png">

**Comment by zakariyaaminullah** [comment]
Finally, I can join the discussion. Something wrong also happened in section number 12 about _Chanda_. It seems that paragraphs consisting of lists of meters cannot be placed between two metrical texts.
<img width="1709" alt="Screen Shot 2022-04-18 at 15 58 42" src="https://user-images.githubusercontent.com/39810661/163819453-e62a3dfb-24c1-48ef-8903-b32a16fd1204.png">

**Comment by ajaniak** [comment]
The display is as expected with the current encoding.

**Comment by arlogriffiths** [comment]
Please explain more clearly what you mean, @ajaniak : 

do you mean the encoding is wrong? 

If not, it must be the display that is wrong, because we don't have a rule (as far as I know) that any prose passages will be displayed only in the space between the width of verse passages and the corresponding apparatus entries. 

If such a rule is in place, it should be removed. The display of verse vs. prose should be as it is in other editions, e.g. Sarasamuccaya:

<img width="984" alt="Capture d’écran 2022-04-19 à 10 42 26" src="https://user-images.githubusercontent.com/835603/163962356-5641a37a-6aef-464e-821c-56134cd26102.png">

**Comment by arlogriffiths** [comment]
It seems the problem is solved now. Great! Just one small infelicity remains for me at this time, concerning display of `<ab type="colophon">`. See screenshot:

<img width="1064" alt="Capture d’écran 2022-04-22 à 08 26 37" src="https://user-images.githubusercontent.com/835603/164616389-63c917dc-5c51-41ed-868b-282553704805.png">


It would be nicer if the displayed heaidng "colophon" were separated by some vertical space from the preceding `<lg>` and if both the heading and the actual colophon stood at the same width as 10.2 and Sūtrasandhi.

**Comment by ajaniak** [comment]
Like this?
![Capture d’écran 2022-07-13 à 14 15 41](https://user-images.githubusercontent.com/33328906/178731241-c84207cb-00b3-40c1-90a0-b650933eda71.png)

**Comment by zakariyaaminullah** [comment]
The new view of colophon seems very nice to me @ajaniak.

**Comment by arlogriffiths** [comment]
yes, that looks nice! thanks. I am closing the issue now.
