### ISSUE TITLE
proper use of @met

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#59]
@zakariyaaminullah : I see in this commit [https://github.com/erc-dharma/tfd-nusantara-philology/commit/5309ec373d50468d4f50e4ed1b7a0cd5beef41b7](url) that you have put `<div type="metrical" met="---+--+-=">` in line 1212 of your CK CritEd file. 

Clearly, you are confused:

1. @met should only be used when you are dealing with verse. Since the words "iti paruṅguniṅ akṣara" are in prose and form a colophon, you should encode them as per EGC §3.3.2.2. 
2. even if these words had been in verse, you cannot use @met="---+--+-=" unless there is a corresponding `<seg type="xml">---+--+-=</seg>` in the file DHARMA_prosodicPatterns_v01.xml. That file is not used to record any random pattern of short/long syllables, but only for actually metrical patterns that are found in more than one line of verse. Since the corresponding `<seg type="xml">` is not found in that file, the result in display is this:

<img width="357" alt="Capture d’écran 2022-04-13 à 06 29 04" src="https://user-images.githubusercontent.com/835603/163100429-20ecbcc5-3f85-4242-ac87-91456ef19700.png">

Let me know if you have questions. Close this issue after you have revised your encoding.

**Comment by arlogriffiths** [comment]
@zakariyaaminullah : please close this issue if you have revised your encoding.

**Comment by ajaniak** [comment]
@zakariyaaminullah  : can you close this, if you are done?
