### ISSUE TITLE
encoding of CK 6.4

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#60]
@zakariyaaminullah:

You have encoded the sentence "liṅ saṅ kavi vruh iṅ mārga" as though it is a single-line stanza and you have not assigned @met. I am not sure which of these two facts is the cause of the problem, but our system does not recognize what you are doing, which is why the display of the stanza number is not joined with the line of verse:

<img width="296" alt="Capture d’écran 2022-04-13 à 06 41 36" src="https://user-images.githubusercontent.com/835603/163102197-6fd2d20a-09ee-4b2d-b9b8-ce0d23a65326.png">

Here is your code:

`<lg xml:id="candrakirana_07.06" n="6">
<l n="a">liṅ saṅ <app><lem wit="#msba #msbb">kavi</lem><rdg wit="#msjb">kāvi</rdg></app>
   <app><lem wit="#msbb">vruh iṅ</lem><rdg wit="#msba">vruhhaṅ</rdg><rdg wit="#msjb">voteṅ</rdg></app>
   <app><lem type="norm">mārga</lem><rdg wit="#msjb #msba #msbb">marga</rdg></app>.</l></lg>`

Questions:
1. are you sure this sentence isn't a prose colophon? If it is a prose colophon, you should encode as per EGC 3.3.2.2.
2. if the fact that the sentence is octosyllabic, like the four preceding lines, is not a coincidence, then why not make it part of the preceding `<lg>` with `<l n="e">`?
3. do you agree that the rhyme (varga/mārga) is an argument in favor of the analysis as a 5-line stanza? 

If we are starting to see elements of rhyme in your text's use of octosyllabic verse, it is a rather interesting fact that deserves commentary (and should be compared wiith Old Sundanese octosyllabic verse, so I am sending this message to @aditiagunawan too).

I am not sure if @ajaniak has foreseen stanzas that do not contain even numbers of lines when she was setting up our system. Let's see what happens if you encode as a 5-line stanza.

**Comment by arlogriffiths** [comment]
I guess the same could be done at the end of 2.1. In fact, maybe you should not divide octosyllabic sections (met="pādānuṣṭubh") into 4-line (and occasionally 5-line) groups at all, but rather group all lines in a single `<lg>` and assign continuous letter-numbering (a, b, c, d, e, f, g ...) for the octosyllabic `<l>`.

@aditiagunawan : do you have an opinion on this matter? (We have to decide whether we shall use the Candrakiraṇa's term Pādānuṣṭubh for free octosyllabic verse, or whether we shall use an emic term like "Free octosyllabic")
@ajaniak : since the octosyllabic verse really does not follow the Sanskrit system at all, could we allow applying the alternative system that I believe we have foreseen for Tamil verse in EGD §2.3.3 ("in Tamil verse, always use Arabic numerals (1, 2, 3, 4)")? If this can be done, then we need a display rule that a `<div>` containing only a single `<lg>` will be displayed without stanza number
@danbalogh : if so, we should should modify EGD 2.3.3 to become "in Tamil verse, as well as in free octosyllabic versification found in some Old Sundanese and Old Javanese works, you should use ..."

For reference, this is the text edition that is inspiring these questions: [https://erc-dharma.github.io/tfd-nusantara-philology/output/critical-edition/html/DHARMA_CritEdCandrakirana.html](url). If you search "Pādānuṣṭubh", you get several hits.

**Comment by aditiagunawan** [comment]
@arlogriffiths 

I would prefer a more general term "free octosyllabic" as you suggest. But I wonder whether this should be relevant to any kind of octosyllabic verse regardless the number of line or whether it has a "stanza" or not. In the habit of Old Sundanese editions, also based on the nature of the texts, the editors never divided a verse text into stanza, so if I imagine to the encoding, the text may contains a thousand of `<l>` within a  single `<lg>`. I am not sure whether the numbering with letter a, b, c, etc will be practical in this case.

**Comment by ajaniak** [comment]
@arlogriffiths a provision for Arabic numeral is already given in §3.4.3. 
Regarding the `<div>` display, I need more precision and context since some editions allow several levels of `<div>`.

**Comment by arlogriffiths** [comment]
@ajaniak : looking at a situation like the one in the screenshot, I suspect the condition of absence of @n on `<lg>` should be abandoned.

<img width="382" alt="Capture d’écran 2022-04-14 à 06 29 18" src="https://user-images.githubusercontent.com/835603/163313920-3d6580ee-3afe-4402-a52e-b128bac1d01f.png">

**Comment by ajaniak** [comment]
What you have asked for should be applied. Note that some features are handled with CSS and can take time to be updated on the server and be displayed on the temporary website. 

A remark on the 2., I don't think adding a feature regarding the display of an edition through an outside file is a great practice. And since you foresee gathering different use for it, I wouldn't recommend the use of `@rend="noPattern"` to `<name xml:lang="eng">free octosyllabic</name>`. So for now, I have use the presence of the term "free" as an indication to avoid the display of the prosody.  If you are fixed on using an attribute to avoid the prosody display, then we should add it on the edition. I guess anyway it would logical since we already have `@rend='met'` to display the prosody.

**Comment by arlogriffiths** [comment]
@ajaniak :

1. could you make a provisional change or comment in the EGC on the use of "free" that you have implemented, so we remember to discuss it later and make a final decision?
2. the layout of verses with numerical values of @n is not yet satisfactory, as the line numbering interferes with the vers numbering, e.g.:

<img width="396" alt="Capture d’écran 2022-04-28 à 05 29 16" src="https://user-images.githubusercontent.com/835603/165670776-5c1a3007-8a8c-4805-8708-8ff2ddce82e7.png">

3. it would be ideal of line numbering could be shown somewhere in the free space between `<div>` numbering and the text of the stanzas; if thay is technically difficult (or if there is another problem that I am currently overlooking), then let's discuss other options.
4. another practical solution to the case of a 5-line verse shown above would be to remove the constraint that an `<lg>` must contain `<l>` with @n values a, b, c and d, so that the 5th line could be `<l n="e">` and no recourse need to be had to numerical values for @n.

**Comment by ajaniak** [comment]
2 & 3. I have moved the lines using CSS for now. It should be applied at some point on the display
4. There is no contraint regarding the value @n as long it is provided it can be Arabic, letters or a mix of both.
