### ISSUE TITLE
problem with fake-lem for <note> to <l>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#61]
See screenshot. Is it just me, or is an extra space inserted in display before `<ptr target="#JK"/>`?

More importantly, the last word of the fake lem is not taken from the `<l>` but from the `<note>`.

<img width="1210" alt="Capture d’écran 2022-04-22 à 09 10 37" src="https://user-images.githubusercontent.com/835603/164624971-3e060060-f563-4708-9fb6-8e47f33b32b4.png">

**Comment by ajaniak** [comment]
Yes, I am aware of the issue. I had to disable the code because it is conflict with other features. 
There is no extra space in the html.

**Comment by ajaniak** [comment]
I has been stabilized for now based on the fake-lem variety in the files. 
<img width="1275" alt="Capture d’écran 2022-04-22 à 14 27 07" src="https://user-images.githubusercontent.com/33328906/164714236-54154e5b-3c18-442b-bde0-5f2af0f8b431.png">

**Comment by arlogriffiths** [comment]
thanks!
