### ISSUE TITLE
refresh xml:id's and @n values of cantos in DHARMA_CritEdKakavinRamavijayaTaningrat.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#63]
Dear Axelle,

I have found a new canto boundary that was not previously encoded, so all numbers starting from canto 60 are wrong.

Can you refresh them? Thanks!

Arlo

**Comment by arlogriffiths** [comment]
Please also refresh Svayambhu.

**Comment by ajaniak** [comment]
Done for both files

**Comment by arlogriffiths** [comment]
Thanks!
