### ISSUE TITLE
espace devant <ptr target="SIGLUM"/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#64]
tu avais dit que j'ai tort, mais je persiste à avoir l'impression qu'il y a une asymétrie dans les espaces devant et après les occurrences des sigles, l'espace devant étant plus importante que celle d'après. voir la note dans le screenshot.

<img width="370" alt="Capture d’écran 2022-05-05 à 06 37 06" src="https://user-images.githubusercontent.com/835603/166864410-0b6fee6e-a7d7-4040-8223-8797ce6cd512.png">

merci de regarder cela de près.

**Comment by arlogriffiths** [comment]
probably related to this, there is excessive white space before sigla in the context of `<pb edRef="..."/>`. see screenshot:

<img width="238" alt="Capture d’écran 2022-05-10 à 06 34 23" src="https://user-images.githubusercontent.com/835603/167543389-54fc5acf-fe56-451f-99e2-2a8d38206516.png">

**Comment by ajaniak** [comment]
I have recoded all the content regarding the siglum. It will take sometimes to be applied on the display though since both the css and the loader are impacted as well as the xslt.

**Comment by arlogriffiths** [comment]
Thanks. I have the feeling that there hasn't been any change yet. See screenshot made just now.

<img width="168" alt="Capture d’écran 2022-06-01 à 17 04 05" src="https://user-images.githubusercontent.com/835603/171436838-ea0cbd00-94bd-43a2-ac60-3de2ca4d68cc.png">

**Comment by ajaniak** [comment]
A comment node was making the parser bug

**Comment by arlogriffiths** [comment]
problem solved, thanks!
