### ISSUE TITLE
@type="absent_elsewhere" not yet effective

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#68]
Sample code 

`ikaṅ <pb edRef="#L" n="10"/>avyavahāra kalih, tan hana kumavruhi vicāranya,
 <app><lem wit="#K #M" type="absent_elsewhere">tātan vruh saṅ <app><lem wit="#K">prāgvivāka</lem><rdg wit="#M">pragivaka</rdg></app> ri hutaṅnya</lem><rdg wit="#L" cause="eye-skip"><gap reason="omitted"/></rdg></app>,
 konən <app><lem wit="#K">asatyaa ikaṅ</lem><rdg wit="#L">hasatyaha:<lb n="10-02"/>kaṅ</rdg><rdg wit="#M">amatyaha ikaṅ</rdg></app> avyavahāra kalih,
 asiṅ vikāra sorakəna pakṣanya.`

The display is not really satisfactory:

<img width="1282" alt="Capture d’écran 2022-06-01 à 17 35 15" src="https://user-images.githubusercontent.com/835603/171443507-0f5800c8-6d8b-4a82-93e3-08b5c9dd5926.png">
<img width="1101" alt="Capture d’écran 2022-06-01 à 17 35 25" src="https://user-images.githubusercontent.com/835603/171443512-40fb2692-baaf-423d-872f-3965a9e94628.png">

Shall we resort to explicit encoding of  `<rdg wit="..."><gap reason="..."/></rdg>` also on the `<app>` within the `<app>`? 

See open discussions in EGC §5.5.10.1, 5.5.11.1 and example 68.

**Comment by ajaniak** [comment]
A first display has been finalized for this

**Comment by arlogriffiths** [comment]
Thanks. I think it works. See screenshots:

<img width="1196" alt="Capture d’écran 2022-06-17 à 15 49 42" src="https://user-images.githubusercontent.com/835603/174322165-f65677c7-8e96-49f5-b693-60ff3d9e0f0a.png">
<img width="1130" alt="Capture d’écran 2022-06-17 à 15 49 50" src="https://user-images.githubusercontent.com/835603/174322203-c6b940d6-7b3e-4576-aff6-d9428af17e7b.png">

It is not so satisfactory that the label (eye-skip) is applied only to the variant reading for the specific lemma prāgvivāka, while the cause is here loghically the fact that the larger segment is missing in L. But I think I should simply have chosen a different encoding here, namely without @absent_elsewhere:

`ikaṅ <pb edRef="#L" n="10"/>avyavahāra kalih,<!-- comma omitted in #K --> tan hana kumavruhi vicāranya,<!-- #L omits , --> <app><lem wit="#K #M">tātan vruh saṅ <app><lem wit="#K">prāgvivāka</lem><rdg wit="#M">pragivaka</rdg></app> ri hutaṅnya</lem><rdg wit="#L" cause="eye-skip"><gap reason="omitted"/></rdg></app>,<!-- #L omits , --> konən <app><lem wit="#K">asatyaa ikaṅ</lem><rdg wit="#L">hasatyaha:<lb n="10-02"/>kaṅ</rdg><rdg wit="#M">amatyaha ikaṅ</rdg></app> avyavahāra kalih, asiṅ vikāra sorakəna pakṣanya.`

Would that still generate apparatus 648? And would the `@cause="eye-skip"` then be displayed only in apparatus 647?

**Comment by arlogriffiths** [comment]
In fact, I now have trouble remembering why I thought we needed a `@type="absent_elsewhere"` at all. Maybe we only need `@type="reformulated_elsewhere"`. Let us discuss during our Thursday session.

**Comment by arlogriffiths** [comment]
Shall we close this issue?
