### ISSUE TITLE
XML to TEX conversion

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#69]
1. `@type="conj"` is not yet processed; it needs to be displayed as _conj._  analogously to @types "emn" and "norm"
2. implement display of `<lacunaStart>...</lacunaEnd>` as well as `<span type="omissionStart">...</span type="omissionEnd">`: use a separate layer of apparatus, like this: "1–8 ndah nihan … kana] gap due to loss in C" or 
"1–8 ndah ni … kana] gap due to omission in C"

**Comment by arlogriffiths** [comment]
3. code `<ptr target="#B"/> ` to be displayed as siglum in bold
4. the siglum in top apparatus layer in phrases such as "gap due to omission in SIGLUM" is to be printed in bold as well

**Comment by aso2101** [comment]
I have now completed all of the requests, and made sure that the Siksa Guru files compile. Please see the folder `transformation` in the [repository](https://github.com/erc-dharma/aditia-phd).

The XML files are now taken from the `tfd-nusantara-philology` repository. I have modified the LaTeX header and reorganized the folder for the sake of easier and more transparent processing. This means that you should use the LaTeX files in `transformation/latex` from now on. I have taken the most recent versions of the files from `These LaTeX`. Please (a) ensure that everything you need is in the new directory, and (b) ensure that you are able to compile the LaTeX file on your own.
