### ISSUE TITLE
unwanted numbers in display of <div type="metrical" >

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#71]
@ajaniak — at the moment, the transformation is inserting subsection numbers for `<div type="metrical" >` that seem to replicate the number of the parent `<div>`. See screenshots. Could we fix as rule that no number is displayed for `<div type="metrical" >` unless a number is explicitly encoded with `@n`?

<img width="476" alt="Capture d’écran 2022-06-20 à 11 23 53" src="https://user-images.githubusercontent.com/835603/174570413-4c88dcf9-a9a1-4b0c-8a62-58a226cc70cc.png">
<img width="708" alt="Capture d’écran 2022-06-20 à 11 24 09" src="https://user-images.githubusercontent.com/835603/174570418-ba430d32-6619-4c50-bdde-942dde9aeddc.png">

**Comment by ajaniak** [comment]
Done
