### ISSUE TITLE
display of colophon

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#72]
@ajaniak — is something wrong with encoding here, in Zaki's Candrakirana file. If not, can the colophon be aligned with the `<head>` of the parent `<div>` and can it be separated from the preceding sibling `<div>` by some white space?

<img width="989" alt="Capture d’écran 2022-06-20 à 12 04 39" src="https://user-images.githubusercontent.com/835603/174579046-67d1aee3-fe3b-4a08-b157-069cb3dc6dd0.png">

**Comment by ajaniak** [comment]
Done
