### ISSUE TITLE
reencode cases of absent_elsewhere

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#74]
cases in Svayambhu and Rsisasana

**Comment by arlogriffiths** [comment]
also reformulated_elsewhere in Siksa Kandang Karesian and Svayambhu

Arlo will make the changes in XML in consultation with Aditia.

Axelle will propose revisions to EGC as per discussion with Arlo on 2022-06-23

**Comment by ajaniak** [comment]
The code is already done

**Comment by arlogriffiths** [comment]
great. we will get to work tomorrow.

**Comment by arlogriffiths** [comment]
1. all cases of absent_elsewhere removed
2. inserted comment in EGC at §5.5.8 asking for a refinement of display of cases of `<app>` within `<app>` in case of a `<gap>` in one of the witnesses
3. cases of reformulated_elswhere left in place, pending further discussion, opened a new issue for this purpose
4. closing this issue.
