### ISSUE TITLE
more on reformulated_elsewhere

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#75]
@ajaniak — I am not yet sure we must gewt rid of this @type.

In any case, the current display leads to some error. See the curious repeition of #L in the apparatus highlighted in this screenshot:

<img width="1656" alt="Capture d’écran 2022-06-24 à 11 17 06" src="https://user-images.githubusercontent.com/835603/175505204-6b2b0722-b5e0-4ea4-825f-a6ec7e7fb5c7.png">

**Comment by arlogriffiths** [comment]
About 7 cases of reformulate_elsewhere remain in Svayambhu and one in Siksa Kdang Karesian. Please take a look at those cases and advise on whether next steps.

**Comment by ajaniak** [comment]
We have discussed two possible solutions

This is the current encoding
```
<app><lem wit="#A" type="reformulated_elsewhere">ya kaṅkən guru <app><lem wit="#B">kautamaan</lem><rdg wit="#A #EdASD">Utama</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kamulyan</lem><rdg wit="#A #EdASD">mulya</rdg></app>, ya kaṅkən guru 
                                  <app><lem wit="#B">kaprəmanaan</lem><rdg wit="#A">primana</rdg><rdg wit="#EdASD">prəmana</rdg></app>, ya kaṅkən guru kaupadesaan</lem><note type="altLem">ya kaṅkən guru utama ... ya kaṅkən guru kaupadesaan</note><rdg wit="#B">ya guru kamulyin· ṅarana guru kaprəmanaAn·, ya kaṁkən· guru kaUtamaAn·</rdg><note>It seems that <ptr target="#B"/> favors forms with circumfix <foreign>ka-...-an</foreign> and arranges the elements in a different sequence, while omitting an element corresponding to <foreign>kaupadesaan</foreign> in <ptr target="#A"/>.</note></app>
```

The first was to keep a generic lem with a @type="reformulation" and the possibility to have all the variants as children

```
<app><lem type="reformulation">ya kaṅkən guru <app><lem wit="#B">kautamaan</lem><rdg wit="#A #EdASD">Utama</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kamulyan</lem><rdg wit="#A #EdASD">mulya</rdg></app>, ya kaṅkən guru 
                                  <app><lem wit="#B">kaprəmanaan</lem><rdg wit="#A">primana</rdg><rdg wit="#EdASD">prəmana</rdg></app>, ya kaṅkən guru kaupadesaan</lem><note type="altLem">ya kaṅkən guru utama ... ya kaṅkən guru kaupadesaan</note><!--<rdg wit="#B">ya guru kamulyin· ṅarana guru kaprəmanaAn·, ya kaṁkən· guru kaUtamaAn·</rdg>--><note>It seems that <ptr target="#B"/> favors forms with circumfix <foreign>ka-...-an</foreign> and arranges the elements in a different sequence, while omitting an element corresponding to <foreign>kaupadesaan</foreign> in <ptr target="#A"/>.</note></app>
```

The second was to adapt <span> as we have done for OmissionStart and OmissionEnd. 

```
<span type="reformulationStart"/><witDetail wit="#A" type="retained"/>ya kaṅkən guru <app><lem wit="#B">kautamaan</lem><rdg wit="#A #EdASD">Utama</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kamulyan</lem><rdg wit="#A #EdASD">mulya</rdg></app>, ya kaṅkən guru 
                                  <app><lem wit="#B">kaprəmanaan</lem><rdg wit="#A">primana</rdg><rdg wit="#EdASD">prəmana</rdg></app>, ya kaṅkən guru kaupadesaan<span type="reformulationEnd"/><!--</lem><note type="altLem">ya kaṅkən guru utama ... ya kaṅkən guru kaupadesaan</note>--><!--<rdg wit="#B">ya guru kamulyin· ṅarana guru kaprəmanaAn·, ya kaṁkən· guru kaUtamaAn·</rdg>--><witDetail wit="#B" type="rejected"></witDetail><note type="reformulation">It seems that <ptr target="#B"/> favors forms with circumfix <foreign>ka-...-an</foreign> and arranges the elements in a different sequence, while omitting an element corresponding to <foreign>kaupadesaan</foreign> in <ptr target="#A"/>.</note>
```
From what we have discussed, I have added @type="reformulation" on the note to make sure, there is no ambiguity with other elements `<note>`.  I have kept the  possibility to declare `<witDetail/> after both `<span>` with an attribute @type="retained" or @type="rejected", as well as the fact that the altlem will be generated automatically. 

Let me know what you think of both, now that we have a clearer view on the encoding. If this works, I will add it in the schema, EGC and then start working on the display. Could you let me know what are you new expectation on this matter?

**Comment by arlogriffiths** [comment]
Thanks for laying it out so clearly. I think we could offer both new approaches, or at least the second one, which will anyhow be necessary if the phenomenon stretches across a block-level container.

Both would need to be modified slightly, I think, in order to display explicitly the B version of the whole sequence, so nd the `<rdg>` should not be hidden. And in the first method, the @wit should also be encoded on the first `<lem>`. This means we'd get this:

`<app><lem wit="A" type="reformulation">ya kaṅkən guru <app><lem wit="#B">kautamaan</lem><rdg wit="#A #EdASD">Utama</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kamulyan</lem><rdg wit="#A #EdASD">mulya</rdg></app>, ya kaṅkən guru 
                                  <app><lem wit="#B">kaprəmanaan</lem><rdg wit="#A">primana</rdg><rdg wit="#EdASD">prəmana</rdg></app>, ya kaṅkən guru kaupadesaan</lem><note type="altLem">ya kaṅkən guru utama ... ya kaṅkən guru kaupadesaan</note><rdg wit="#B">ya guru kamulyin· ṅarana guru kaprəmanaAn·, ya kaṁkən· guru kaUtamaAn·</rdg><note>It seems that <ptr target="#B"/> favors forms with circumfix <foreign>ka-...-an</foreign> and arranges the elements in a different sequence, while omitting an element corresponding to <foreign>kaupadesaan</foreign> in <ptr target="#A"/>.</note></app>`

The display should have "Thus formulated in A" behind the lemma, as in the current display of reformulated_elsewhere.

The second method would have to be modified analogously, to be able to display the full reading of the rejected witness. The display should also be analogous, but (as in other cases of `<span>`) there should be an indication of where the span ends.

By the way, could we do `<witDetail wit="#B" type="rejected"/>` instead of `<witDetail wit="#B" type="rejected"></witDetail>`?

Hope this sounds good to you. Let me know if it raises further questions.

**Comment by arlogriffiths** [comment]
FYI, at the moment some behavior which does not belong to reformulated_elsewhere is observed in the display. See (larger gap) in this screenshot:

<img width="1572" alt="Capture d’écran 2022-06-25 à 09 14 20" src="https://user-images.githubusercontent.com/835603/175762974-283cde66-7785-405f-8f2a-6345c3329b1d.png">

**Comment by ajaniak** [comment]
We decided to get ride of the `@wit` on the main `<lem>` to avoid model issue arising when declaring it. So if you want to keep this declaration, then we could move it to a `<witDetail>`

```
<app><lemtype="reformulation">ya kaṅkən guru <app><lem wit="#B">kautamaan</lem><rdg wit="#A #EdASD">Utama</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kamulyan</lem><rdg wit="#A #EdASD">mulya</rdg></app>, ya kaṅkən guru <app><lem wit="#B">kaprəmanaan</lem><rdg wit="#A">primana</rdg><rdg wit="#EdASD">prəmana</rdg></app>, ya kaṅkən guru kaupadesaan</lem><witDetail wit="A" type="retained"/><note type="altLem">ya kaṅkən guru utama ... ya kaṅkən guru kaupadesaan</note><rdg wit="#B">ya guru kamulyin· ṅarana guru kaprəmanaAn·, ya kaṁkən· guru kaUtamaAn·</rdg><note>It seems that <ptr target="#B"/> favors forms with circumfix <foreign>ka-...-an</foreign> and arranges the elements in a different sequence, while omitting an element corresponding to <foreign>kaupadesaan</foreign> in <ptr target="#A"/>.</note></app>
```

In a way, it would allow to handle both solution in a closer manner. 
And yes, `<witDetail/>` can be declared as an empty element.

**Comment by ajaniak** [comment]
The larger gap display should be resolved for the embedded variants with reformulated elsewhere.

**Comment by arlogriffiths** [comment]
Thanks a lot. I am not sure I understand the model problem, though the solution with witDetail looks fine. Let's disscuss and finalize this issue on Thursday.

**Comment by arlogriffiths** [comment]
@aditiagunawan : we have just edited your SKK xml file and implemented the last proposal. Please doi git pull. Axelle will soon update the schema to allow the @type="reformulation".

**Comment by arlogriffiths** [comment]
As the moment, `<witDetail type="retained"/>` does not yet generate the phrase "Thus formulate in ..." in the display of the apparatus. See screenshot: 
<img width="1310" alt="Capture d’écran 2022-07-08 à 08 09 40" src="https://user-images.githubusercontent.com/835603/177927945-923c6469-b713-4161-9402-544cd2234f9b.png">

**Comment by arlogriffiths** [comment]
@ajaniak : I have finished revising Svayambhu. Once I have your response to the proposal

`<app> <lem type="conj">cakravr̥ddhi <supplied reason="omitted">kālavr̥ddhi kārikāvr̥ddhi</supplied> kāyikāvr̥ddhi</lem> <rdg wit="#L">cakravr̥di, kayika:vr̥di</rdg> <rdg wit="#K">cakr̥vradi ṅaranika:, Ana: kayika:vr̥di</rdg> <rdg wit="#M"><span type="omissionEnd"/> hana kayikavrədi</rdg> </app>`

and you have fixed the small display issue pointed out just above, we can close this issue.

**Comment by arlogriffiths** [comment]
The phrase "Thus formulated in ..." is now included in the display. Thanks! 

Every also works even in a more comoplicated casse, where one witness is affected by a larger gap:

<img width="342" alt="Capture d’écran 2022-07-08 à 08 43 56" src="https://user-images.githubusercontent.com/835603/177932831-27639bb4-f9b9-4969-a3b4-93ea5cec79e3.png">

<img width="647" alt="Capture d’écran 2022-07-08 à 08 45 05" src="https://user-images.githubusercontent.com/835603/177932968-6f86a8d6-79e3-4586-8aca-25b00f283127.png">


So the only remaining issue is the encoding proposal above.

**Comment by ajaniak** [comment]
I think you checked the display before any transformation was made. 

Your proposal seem ok to me, if you feel it is enough to represent this transmission.
