### ISSUE TITLE
Checking the updated teiHeader

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#78]
Dear all, 

Could you check the updated versions of the `<teiHeader>`that has been applied on some of the editions for `<witness>`, please?  It was mostly focused on providing a more detailed content for `<msIdentifier>`.
For instance, we started there
```
<witness xml:id="C">Gebang, Ciburuy, Kropak 22 peti 2c
                  <abbr type="siglum">C
                  </abbr>
</witness>
```
to go there
```
<witness xml:id="C">
                  <abbr type="siglum">C</abbr>
                  <msDesc>
                     <msIdentifier>
                        <settlement>Ciburuy</settlement>
                        <collection>Gebang</collection>
                        <idno>Kropak 22 peti 2c</idno>
                     </msIdentifier>
                  </msDesc>
               </witness>
```
 I am not sure to have interpreted all the data correctly and when data were not available, i couldn't fill them. 

List of the modified files: 
- [x] DHARMA_CritEdPurvadhigama
- [x] DHARMA_CritEdSangHyangHayu
- [x] DHARMA_CritEdSarasamuccayaVararuci
- [x] DHARMA_CritEdSasanaMahaguru
- [x] DHARMA_CritEdSvayambhu

Best,

**Comment by aditiagunawan** [comment]
@arlogriffiths @ajaniak 
done!
