### ISSUE TITLE
encoding colophon

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#79]
Dear all, 

Could you applied the new encoding rules on the `<colophon>` element inside the teiHeader? See EGC, §2.1.3, end of the page 21. 

I have already added the elements `<quote>`
- [ ] DHARMA_CritEdBhimaSvarga
- [x] DHARMA_CritEdCandrakirana
- [ ] DHARMA_CritEdSiksaGuru

Best,

**Comment by arlogriffiths** [comment]
@aditiagunawan : please carry out this task and then close the issue.

**Comment by aditiagunawan** [comment]
@arlogriffiths @ajaniak 

When I choose type="diplomatic" in `<colophon>`, I can not apply the element `<choice>`, `<sic>` etc. Should I leave the diplomatic reading without intervention or rather choose the `<normalized>` in this case? 

Thanks!

**Comment by arlogriffiths** [comment]
The idea was that you would strictly give the text as it found in the witness in `<quote  type="diplomatic">` and that you'd then give the normalized version in `<quote  type="normalized">`.

I am not sure what @ajaniak think about admitting `<choice>` in `<quote  type="diplomatic">`. If she has no objection, then we can allow it and there may not be a need to  furnish a `<quote  type="normalized">` in case some corrections/normalizations are made in `<quote  type="diplomatic">` itself. 

But I'd like to keep the option of separating diplomatic and normalized representations in the manner we had foreseen.

**Comment by ajaniak** [comment]
As @arlogriffiths, I thought we would separate diplomatic and normalized representations. But if you need it, i have added it in the schema and in the display following the conventions we have set for inscriptions

**Comment by ajaniak** [comment]
It has been applied so I am closing this
