### ISSUE TITLE
critical editions template

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#8]
@ajaniak and @GiuliaBhu : I have changed the file name and made some small edits to the contents of the draft Template for encoding critical editions, which is now here:

[https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/DHARMA_templateCriticalEditions_v01.xml](https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/DHARMA_templateCriticalEditions_v01.xml)

@ajaniak : would it not be better to move it into [https://github.com/erc-dharma/project-documentation/tree/master/templates](https://github.com/erc-dharma/project-documentation/tree/master/templates)? If you agree, please move the file there and close this issue. If you disagree, please explain.

**Comment by ajaniak** [comment]
done
