### ISSUE TITLE
teiHeader: insert space between display of <forename> and <surname>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#81]
@ajaniak : can you make sure a space get inserted between `<forename>` and `<surname>`?

<img width="774" alt="Capture d’écran 2022-07-02 à 15 25 28" src="https://user-images.githubusercontent.com/835603/177002836-89233c8c-291a-4170-a007-3136b96e9ec2.png">

Also, why is there a "," before the version's date? And what does the Z mean?

**Comment by ajaniak** [comment]
I have updated the rules for the draft display and the structure of `<editor>` element. 
The Z is resulting from a time code issue of the current-time() fonction. Since it is temporary, it is not worth investing time for lines of code handling it better.

**Comment by arlogriffiths** [comment]
thanks!
