### ISSUE TITLE
error in schema?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#82]
at the moment, Zaki's file does not  validate but we don't understand the error...

<img width="1449" alt="Capture d’écran 2022-07-04 à 10 46 14" src="https://user-images.githubusercontent.com/835603/177118233-16beea22-1979-448a-9265-5b791f741c05.png">

**Comment by ajaniak** [comment]
It should be good now

**Comment by arlogriffiths** [comment]
Thanks.

@zakariyaaminullah : can you close this if the error message has indeed disappeared on your side? If it hasn't, maybe a zoom session with Axelle will be useful to see what's going on.

**Comment by arlogriffiths** [comment]
@zakariyaaminullah : please close this issue if the problem has gone away after restarting Atom.
