### ISSUE TITLE
brackets out of place?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#83]
Dear bugbuster @ajaniak ! Here is a first little report on a minor imperfection to  be corrected — no hurry.

<img width="1429" alt="Capture d’écran 2022-07-06 à 07 59 54" src="https://user-images.githubusercontent.com/835603/177479756-ae6b0378-05a5-4c38-93c0-170e1829b004.png">

The [] to mark "text to be supplied unknown to editor" should be aligned with the left end of supplied stanza in the next section.

**Comment by ajaniak** [comment]
I have reworked on the structure for ab yesterday so that colophon and invocation are aligned on the numbers. I have added conditions on the structure, the brackets for supplied base text should in place again.
