### ISSUE TITLE
why have you used @real?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#85]
@zakariyaaminullah :

I don't understand why your XML file shows @real in these cases, which seem to be metrically regular. Please check.

<img width="1294" alt="Capture d’écran 2022-07-07 à 11 37 16" src="https://user-images.githubusercontent.com/835603/177743374-78b7ff9d-049c-4994-8768-7cc46f98268d.png">
<img width="1275" alt="Capture d’écran 2022-07-07 à 11 38 31" src="https://user-images.githubusercontent.com/835603/177743408-d6245ec1-15a1-459e-a62d-d5c1dba3f23d.png">

Maybe it's an imperfection in the tex>xml conversion process carried out by Axelle?

**Comment by zakariyaaminullah** [comment]
Those were provided by Axelle in the earlier version of the critical edition XML, and I forgot to eliminate them.
