### ISSUE TITLE
behavior of apparatus

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#86]
at the moment, the display by clicking on the marginal note number doesn't work as it should. a click leads directly to the apparatus at the bottom of the file

**Comment by arlogriffiths** [comment]
yes, now that problem seems to have gone, but I see that the autogeneration of rdg entries within larger gap now doesn't work as it should. see screenshot. the indication for wit="#K" is missing.

<img width="1411" alt="Capture d’écran 2022-07-13 à 14 28 43" src="https://user-images.githubusercontent.com/835603/178733777-39e2a459-3f69-4e62-85cb-f2e9f3bc7046.png">

**Comment by ajaniak** [comment]
So it seems to work on google Chrome and Safari, but not on firefox because of security updates. I will see what I can do to resolve this quickly.

**Comment by ajaniak** [comment]
It should be good now

**Comment by ajaniak** [comment]
@arlogriffiths do you still have this issue or can it be closed?

**Comment by arlogriffiths** [comment]
problem gone, thanks!
