### ISSUE TITLE
Absent of translation button in the verses

### ISSUE THREAD

**Issue by aditiagunawan** [erc-dharma/tfd-nusantara-philology#87]
Dear Axelle,

Following email with Arlo, I want to draw your attention to the absent of "translation" button in the verses part on the prose text DHARMA_CritEdSiksaGuru.html (see figure) which is usually found for `<p>`. Thus, even if I provide a translation corresponding to these verses in my xml file of translation, it won't trigger any transformation. Am I forgetting something on the encoding? 

Thank you,

<img width="1199" alt="Screenshot 2022-08-01 at 16 58 35" src="https://user-images.githubusercontent.com/55530631/182125695-8c751c30-ceba-47fd-99de-26be821d561f.png">

**Comment by ajaniak** [comment]
Dear Aditia, 

I have added the button for the display
![Capture d’écran 2022-08-01 à 13 58 45](https://user-images.githubusercontent.com/33328906/182143134-1917853c-12f0-49c0-8295-3d1df510f665.png)

I don't have time right now to make it better, but I plan in the next days to refine it for cases when parallels and translations are both available.
Does it solve your issue?

**Comment by aditiagunawan** [comment]
Yes Axelle, now it solves. Thank you.
