### ISSUE TITLE
why does the schema not complain about misplaced <listApp>?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#88]
see screenshot. Aditia and I are correcting this encoding error now, by moving `<listApp>` into the `<lg>`.
but is it possible for the schema to indicate such encoding invalid?

<img width="1398" alt="Capture d’écran 2022-08-15 à 11 06 45" src="https://user-images.githubusercontent.com/835603/184575570-9f40cd78-44ee-4d79-bb17-048451105f84.png">

**Comment by arlogriffiths** [comment]
Actually, just moving `<listApp type="parallels">` into `<lg>` leads to invalidation, and the only solution currently working to add`<quote>`. I don't understand why.  See EGC 6.2.1: "The `<listApp type="parallels">` will be the last ... element before the closing tag of the block containing the text for which a parallel will be reported, namely `<p>` or `<lg>`.

**Comment by ajaniak** [comment]
This rule have been changed. I am closing this.
