### ISSUE TITLE
please insert a comment into an xml file

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#89]
Dear @ajaniak !

@nurmaliahabibah and I have made some progress today with Malia's diplomatic edition. Besides several other things, we have inserted after the line `<pb n="60r"/><!-- 119 -->` the comment `<!-- status: not yet checked -->`. Could you insert the same comment after every line containing a `<pb>`? The idea is that Malia will remove such comments gradually, as she makes progress cleaning up the file and checking the manuscript.

Thanks!

Arlo

**Comment by ajaniak** [comment]
I have added the comment after every `<pb/>` in the file.

**Comment by arlogriffiths** [comment]
Thanks!
