### ISSUE TITLE
second editor not shown in display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfd-nusantara-philology#9]
code:

`<editor ref="part:argr">
					<forename>Arlo</forename>
					<surname>Griffiths</surname>
				</editor>
				<editor ref="part:tilu">
					<forename>Timothy</forename>
					<surname>Lubin</surname>
				</editor>`

current display:

<img width="479" alt="Capture d’écran 2021-02-12 à 14 29 38" src="https://user-images.githubusercontent.com/835603/107774034-c971a400-6d3e-11eb-92a7-e13fde14d224.png">

@ajaniak : please implement a pattern FORENAME SURNAME & FORENAME SURNAME or, if there are more than two editors, FORENAME SURNAME, FORENAME SURNAME & FORENAME SURNAME .

**Comment by ajaniak** [comment]
It is done. Can you check to make sure it matches what you were asking?

**Comment by arlogriffiths** [comment]
thanks! looks good!

<img width="1130" alt="Capture d’écran 2021-03-12 à 13 21 55" src="https://user-images.githubusercontent.com/835603/110939604-f4e3b080-8335-11eb-8263-31d286d47145.png">
