### ISSUE TITLE
DiplEd – fw placement

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#92]
Need to move the `<apply-templates/>` for the element `<fw>`. 

<img width="1047" alt="Capture d’écran 2022-11-22 à 11 01 21" src="https://user-images.githubusercontent.com/33328906/203285293-042606ca-3f5d-4160-9056-5e0786198909.png">

**Comment by ajaniak** [comment]
Done

**Comment by arlogriffiths** [comment]
what I see now is this:

<img width="1203" alt="Capture d’écran 2023-02-01 à 19 18 02" src="https://user-images.githubusercontent.com/835603/216060669-3e8d9ad8-3b6a-4610-b214-3d6b0011c27f.png">

the treatment of `<fw>` does not yet seem fully satisfactory.

**Comment by ajaniak** [comment]
Sure you are working with a previous display and not the last one
<img width="282" alt="Capture d’écran 2023-02-01 à 14 58 49" src="https://user-images.githubusercontent.com/33328906/216063268-8a2ae544-d974-46e5-b299-3c3cacd9d738.png">

**Comment by ajaniak** [comment]
closing this since the asked display has changed see project-documentation 204
