### ISSUE TITLE
DiplEd - issue in the display or in the encoding? 

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#96]
Checking the situation in DHARMA_DiplEdKutaraManavaManchesterB2.xml

Is a `<subst>`missing or do I need to add conditions in the code? 

<img width="1004" alt="Capture d’écran 2022-11-22 à 11 25 14" src="https://user-images.githubusercontent.com/33328906/203290316-ca475d5e-8d3d-4a4d-97f9-8450fb6b30c9.png">

**Comment by ajaniak** [comment]
Another example in Zaki's : `<add place="below" rend="mark"><del>ki</del></add>`
<img width="969" alt="Capture d’écran 2022-11-22 à 11 36 06" src="https://user-images.githubusercontent.com/33328906/203292408-fa89fc54-b9bc-40a3-a6ce-fcf7a218f02d.png">

**Comment by arlogriffiths** [comment]
for the case in DHARMA_DiplEdKutaraManavaManchesterB2.xml, there are indeed deletions being made in the sublinear additions. this photo shows what the scribe was doing.

<img width="802" alt="Capture d’écran 2022-11-24 à 06 40 13" src="https://user-images.githubusercontent.com/835603/203664238-7b381398-4ad7-4219-9253-522ebdaf19dc.png">

the TEI encoding is:

` <subst><del>lavan a</del><add place="below"><del>ha</del>lavan a</add></subst>kon amama:liṁ <subst><del>hīka:</del> <add place="below"><del>ṅa</del>hika,</add></subst>,`

this expresses the correct meaning, in my opinion. I am adding @danbalogh so he can check whether the EGD foresees such cases. 

@ajaniak : for Zaki's case, could you contact him?

**Comment by danbalogh** [comment]
I agree with the encoding. Display should be possible to implement with the deletion markers inside the addition markers. The EGD does not explicitly cater for such cases, and I myself think doing so would be a needless complication. It does say (§4.4.1) that "the contents of this element [i.e. `<add>`] may include additional markup, e.g. for reading difficulties" and indeed, any element I can think of could occur within an `<add>`, for instance, `<g>` or `<supplied>`; even `<add>` or another layer of `<subst>` might potentially occur within `<add>`. All of these should be displayed normally, within the markers for addition.
