### ISSUE TITLE
lost, omitted and reformulated

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfd-nusantara-philology#99]
Dear @aditiagunawan,

for `<lem type="lost_elsewhere">`, `<lem type="omitted_elsewhere">` and `<lem type="reformulated_elsewhere">`, the witnesses must be declared in a `<witDetail/>` following the `<lem>` when several `<app>` are embedded. I have added the element in the three files related to your PhD, but I can't filled in the right witnesses. Can you check them please? 

Best,

**Comment by arlogriffiths** [comment]
@aditiagunawan — please react as soon as possible and let us know when you're done.

**Comment by aditiagunawan** [comment]
@ajaniak 
Done, please check.

**Comment by arlogriffiths** [comment]
is only one file concerned?

**Comment by aditiagunawan** [comment]
I have checked all three files.

**Comment by arlogriffiths** [comment]
@ajaniak : please close this if this issue is effectively resolved.

**Comment by ajaniak** [comment]
Looks good to me. Thanks @aditiagunawan!
